import type { Module } from '@/types';

export const modules: Module[] = [
  // ── Phase 1: Foundations ──────────────────────────────────────────────────
  {
    id: 'mod-001',
    slug: 'what-is-ai',
    phaseSlug: 'phase-1-foundations',
    title: 'What Is AI?',
    description:
      'Demystify artificial intelligence. Understand what AI actually is, how it differs from ML and generative AI, and why it matters right now.',
    longDescription:
      'This first module cuts through the hype and gives you a grounded, honest mental model of AI. You will understand the difference between traditional software and AI, see where AI excels and fails, and gain the vocabulary to talk confidently about it.',
    order: 1,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '🤖',
    tags: ['foundations', 'ai-basics', 'mental-models'],
    lessonSlugs: [
      'ai-vs-ml-vs-generative-ai',
      'how-llms-work-simply',
      'what-ai-can-and-cannot-do',
      'ai-in-everyday-life',
    ],
    isOptional: false,
    whatYouLearn: [
      'The difference between AI, ML, and Generative AI',
      'How large language models (LLMs) work at a high level',
      'What AI is genuinely good and bad at',
      'Where AI already shows up in your daily life',
    ],
  },
  {
    id: 'mod-002',
    slug: 'ai-tools-overview',
    phaseSlug: 'phase-1-foundations',
    title: 'AI Tools Overview',
    description:
      "Explore the landscape of today's AI tools — chatbots, image generators, coding assistants, and more. Know which tool to reach for and when.",
    order: 2,
    difficulty: 'beginner',
    estimatedHours: 1.5,
    icon: '🛠️',
    tags: ['tools', 'chatgpt', 'claude', 'gemini', 'comparison'],
    lessonSlugs: ['chatbot-landscape', 'choosing-the-right-tool'],
    isOptional: false,
    prerequisites: ['what-is-ai'],
    whatYouLearn: [
      'Overview of the major AI chatbots and what makes each unique',
      'Image, audio, video, and code-generation tools',
      'How to quickly evaluate a new AI tool',
      'Free vs paid: what matters for beginners',
    ],
  },
  {
    id: 'mod-003',
    slug: 'prompting-basics',
    phaseSlug: 'phase-1-foundations',
    title: 'Prompting Basics',
    description:
      'Learn how to write clear, effective prompts. Master the techniques that get dramatically better results from any AI tool.',
    order: 3,
    difficulty: 'beginner',
    estimatedHours: 2.5,
    icon: '✍️',
    tags: ['prompting', 'prompt-engineering', 'communication'],
    lessonSlugs: ['anatomy-of-a-good-prompt', 'prompt-patterns', 'common-prompting-mistakes', 'system-prompts-and-custom-instructions'],
    isOptional: false,
    prerequisites: ['what-is-ai'],
    whatYouLearn: [
      'The anatomy of an effective prompt (CRTF framework)',
      'Context, role, tone, and format instructions',
      'Iterating and refining prompts for better results',
      'The most common prompting mistakes and how to avoid them',
    ],
  },
  // ── Phase 2: Key Concepts ──────────────────────────────────────────────────
  {
    id: 'mod-004',
    slug: 'understanding-llms',
    phaseSlug: 'phase-2-key-concepts',
    title: 'Understanding LLMs',
    description:
      'Go deeper on how large language models work — tokens, context windows, temperature, and why these concepts change how you use AI tools.',
    order: 4,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '🔬',
    tags: ['llms', 'tokens', 'context-window', 'temperature'],
    lessonSlugs: ['tokens-explained', 'context-window-deep-dive'],
    isOptional: false,
    prerequisites: ['what-is-ai'],
    whatYouLearn: [
      'What tokens are and why they matter for limits and costs',
      'How context windows affect AI memory and behavior',
      'What temperature controls and when to adjust it',
      'Why different models behave differently on the same prompt',
    ],
  },
  {
    id: 'mod-005',
    slug: 'hallucinations-and-accuracy',
    phaseSlug: 'phase-2-key-concepts',
    title: 'Hallucinations & Accuracy',
    description:
      'Understand why AI confidently makes things up — and build the habits to catch it before it causes problems.',
    order: 5,
    difficulty: 'beginner',
    estimatedHours: 1.5,
    icon: '🔍',
    tags: ['hallucination', 'accuracy', 'verification', 'fact-checking'],
    lessonSlugs: ['ai-hallucination-deep-dive', 'evaluating-ai-output'],
    isOptional: false,
    prerequisites: ['understanding-llms'],
    whatYouLearn: [
      'Why hallucination is a fundamental property of LLMs, not a bug',
      'The different types and levels of hallucination',
      'When hallucination is most dangerous',
      'A practical verification habit you can use every day',
    ],
  },
  // ── Phase 3: Tools in Depth ────────────────────────────────────────────────
  {
    id: 'mod-006',
    slug: 'chatbots-in-depth',
    phaseSlug: 'phase-3-tools-in-depth',
    title: 'Chatbots in Depth',
    description:
      'Get to know the major AI chatbots in detail — ChatGPT, Claude, Gemini, and Perplexity — and understand which excels at what.',
    order: 6,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '💬',
    tags: ['chatgpt', 'claude', 'gemini', 'perplexity', 'comparison'],
    lessonSlugs: ['chatgpt-guide', 'model-comparison', 'ai-for-coding'],
    isOptional: false,
    prerequisites: ['ai-tools-overview'],
    whatYouLearn: [
      'ChatGPT features, strengths, and best-use scenarios',
      "Claude's advantages for long documents and careful reasoning",
      'How to compare models for your specific needs',
      'Free vs paid: when upgrading is worth it',
    ],
  },
  {
    id: 'mod-007',
    slug: 'research-and-search-tools',
    phaseSlug: 'phase-3-tools-in-depth',
    title: 'AI Research & Search Tools',
    description:
      'Use AI to research topics faster and more thoroughly — while keeping your fact-checking instincts sharp.',
    order: 7,
    difficulty: 'beginner',
    estimatedHours: 1.5,
    icon: '🔎',
    tags: ['research', 'perplexity', 'search', 'fact-checking'],
    lessonSlugs: ['ai-for-research'],
    isOptional: false,
    prerequisites: ['ai-tools-overview'],
    whatYouLearn: [
      'Why Perplexity is better than ChatGPT for factual research',
      'How to use AI synthesis alongside primary sources',
      'A simple fact-checking workflow for AI-assisted research',
      'Evaluating AI research quality critically',
    ],
  },
  {
    id: 'mod-008',
    slug: 'writing-and-content-tools',
    phaseSlug: 'phase-3-tools-in-depth',
    title: 'AI Writing & Content Tools',
    description:
      'Use AI as a writing partner that helps you draft, edit, and refine without losing your voice.',
    order: 8,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '📝',
    tags: ['writing', 'editing', 'content', 'style'],
    lessonSlugs: ['ai-writing-assistant', 'editing-with-ai'],
    isOptional: false,
    prerequisites: ['prompting-basics'],
    whatYouLearn: [
      'How to use AI to accelerate your writing without sounding robotic',
      'Editing, rewriting, and tone adjustment with AI',
      'Preserving your voice when using AI help',
      'What AI writing tools are best for what writing types',
    ],
  },
  // ── Phase 4: Advanced Prompting ────────────────────────────────────────────
  {
    id: 'mod-009',
    slug: 'advanced-prompting',
    phaseSlug: 'phase-4-advanced-prompting',
    title: 'Advanced Prompting Techniques',
    description:
      'Go beyond basic prompts. Master chain-of-thought reasoning, few-shot examples, and role-play personas.',
    order: 9,
    difficulty: 'intermediate',
    estimatedHours: 2.5,
    icon: '🧪',
    tags: ['chain-of-thought', 'few-shot', 'role-play', 'prompt-engineering'],
    lessonSlugs: ['chain-of-thought-prompting', 'few-shot-prompting'],
    isOptional: false,
    prerequisites: ['prompting-basics'],
    whatYouLearn: [
      'Chain-of-thought prompting and why it dramatically improves reasoning',
      'Few-shot examples: showing the AI what you want',
      'Role-play and persona prompting for consistent output styles',
      'When to use each technique and how to combine them',
    ],
  },
  {
    id: 'mod-010',
    slug: 'ai-workflows',
    phaseSlug: 'phase-4-advanced-prompting',
    title: 'Building AI Workflows',
    description:
      'Turn one-off AI interactions into repeatable, reliable workflows you can run in minutes.',
    order: 10,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '🔄',
    tags: ['workflows', 'templates', 'prompt-chaining', 'productivity'],
    lessonSlugs: ['building-your-first-workflow'],
    isOptional: false,
    prerequisites: ['advanced-prompting'],
    whatYouLearn: [
      'What an AI workflow is and why it saves time',
      'How to chain prompts for multi-step tasks',
      'Building a reusable prompt template system',
      'Output formatting for structured, consistent results',
    ],
  },
  // ── Phase 5: Automation & Agents ───────────────────────────────────────────
  {
    id: 'mod-011',
    slug: 'automation-basics',
    phaseSlug: 'phase-5-automation-agents',
    title: 'AI Automation Basics',
    description:
      'Learn how to automate repetitive tasks using AI tools, no-code platforms, and simple workflows that save hours every week.',
    order: 11,
    difficulty: 'intermediate',
    estimatedHours: 3,
    icon: '🤖',
    tags: ['automation', 'workflows', 'no-code', 'productivity', 'zapier'],
    lessonSlugs: ['what-is-ai-automation', 'no-code-automation-tools', 'ai-for-data-analysis'],
    isOptional: false,
    prerequisites: ['ai-workflows'],
    whatYouLearn: [
      'What AI automation is and how it differs from traditional scripting',
      'No-code tools: Zapier, Make, and n8n explained simply',
      'Building your first automated AI workflow',
      'Identifying which tasks in your work are good automation candidates',
    ],
  },
  {
    id: 'mod-012',
    slug: 'agents-introduction',
    phaseSlug: 'phase-5-automation-agents',
    title: 'AI Agents',
    description:
      'Understand what AI agents are, how they work, and when they are useful — without needing to write a single line of code.',
    order: 12,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '🤖',
    tags: ['agents', 'agentic-ai', 'tool-calling', 'autonomy'],
    lessonSlugs: ['what-are-agents', 'how-agents-work'],
    isOptional: false,
    prerequisites: ['automation-basics'],
    whatYouLearn: [
      'What an AI agent is versus a simple chatbot',
      'How agents use tools, memory, and planning',
      'Real use cases: research agents, personal assistants, coding agents',
      'Risks and limitations of autonomous AI agents',
    ],
  },
  {
    id: 'mod-013',
    slug: 'tool-calling-basics',
    phaseSlug: 'phase-5-automation-agents',
    title: 'Tool Calling & Skills',
    description:
      'Understand how AI agents use external tools — calculators, search, APIs — and what skills and plugins add to the picture.',
    order: 13,
    difficulty: 'intermediate',
    estimatedHours: 1.5,
    icon: '🔧',
    tags: ['tool-calling', 'skills', 'plugins', 'apis'],
    lessonSlugs: ['what-is-tool-calling'],
    isOptional: true,
    skipLabel: 'Skip if you are not using agent-based tools yet',
    prerequisites: ['agents-introduction'],
    whatYouLearn: [
      'What tool calling means for AI systems',
      'How AI uses calculators, search engines, and APIs as tools',
      'The difference between skills, plugins, and tools',
      'What this technology enables for everyday users',
    ],
  },
  // ── Phase 6: Safety ────────────────────────────────────────────────────────
  {
    id: 'mod-014',
    slug: 'safety-and-limitations',
    phaseSlug: 'phase-6-safety',
    title: 'AI Limitations & Safe Use',
    description:
      'Build a clear-eyed view of what AI cannot do — and develop habits that protect you from common pitfalls.',
    order: 14,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '⚠️',
    tags: ['safety', 'limitations', 'fact-checking', 'responsible-ai'],
    lessonSlugs: ['ai-limitations', 'critical-evaluation'],
    isOptional: false,
    prerequisites: ['prompting-basics'],
    whatYouLearn: [
      'All the key limitations of current AI beyond hallucination',
      'When AI is most likely to mislead you',
      'A practical output evaluation framework',
      'Habits that make you a safer, smarter AI user',
    ],
  },
  {
    id: 'mod-015',
    slug: 'privacy-and-data',
    phaseSlug: 'phase-6-safety',
    title: 'Privacy & Data Protection',
    description:
      'Know what AI tools collect, what you should never share, and how to use AI responsibly with sensitive information.',
    order: 15,
    difficulty: 'beginner',
    estimatedHours: 1.5,
    icon: '🔒',
    tags: ['privacy', 'data', 'security', 'enterprise'],
    lessonSlugs: ['protecting-your-data', 'ai-and-copyright'],
    isOptional: false,
    prerequisites: ['safety-and-limitations'],
    whatYouLearn: [
      'What data AI tools collect and how it is used',
      'What you should never paste into a chatbot',
      'Privacy-friendly AI options and enterprise tiers',
      'Building a personal data protection policy for AI use',
    ],
  },
  // ── Phase 7: Intermediate Systems ──────────────────────────────────────────
  {
    id: 'mod-016',
    slug: 'rag-and-memory',
    phaseSlug: 'phase-7-intermediate-systems',
    title: 'RAG & AI Memory',
    description:
      'Learn how AI can search your documents, remember context, and give you answers grounded in your own data.',
    order: 16,
    difficulty: 'intermediate',
    estimatedHours: 2.5,
    icon: '🗄️',
    tags: ['rag', 'retrieval', 'memory', 'knowledge-bases'],
    lessonSlugs: ['rag-explained'],
    isOptional: true,
    skipLabel: 'Skip if you only use general-purpose chatbots',
    prerequisites: ['prompting-basics'],
    whatYouLearn: [
      'What RAG (Retrieval-Augmented Generation) is and why it matters',
      'How AI memory works conceptually',
      'Practical tools for building knowledge bases with AI',
      'When to use RAG vs fine-tuning vs system prompts',
    ],
  },
  {
    id: 'mod-017',
    slug: 'embeddings-and-vectors',
    phaseSlug: 'phase-7-intermediate-systems',
    title: 'Embeddings & Vector Databases',
    description:
      'Understand the technology behind semantic search — how AI represents meaning as numbers and finds similar content.',
    order: 17,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '🔢',
    tags: ['embeddings', 'vector-databases', 'semantic-search'],
    lessonSlugs: ['embeddings-simply'],
    isOptional: true,
    skipLabel: 'Skip unless you are building or evaluating RAG systems',
    prerequisites: ['rag-and-memory'],
    whatYouLearn: [
      'What embeddings are and why they are foundational to modern AI',
      'How vector databases store and search meaning',
      'Semantic search vs keyword search — why AI search feels magical',
      'How this powers tools like Notion AI, Perplexity, and custom chatbots',
    ],
  },
  // ── Phase 8: Advanced Modern AI ────────────────────────────────────────────
  {
    id: 'mod-018',
    slug: 'mcp-and-skills',
    phaseSlug: 'phase-8-advanced-ai',
    title: 'MCP, Skills & Plugins',
    description:
      'Understand MCP (Model Context Protocol), AI skills, and plugins — the modern infrastructure connecting AI to your tools and data.',
    order: 18,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '🔌',
    tags: ['mcp', 'skills', 'plugins', 'tool-calling', 'integration'],
    lessonSlugs: ['what-is-mcp', 'ai-skills-explained'],
    isOptional: true,
    skipLabel: 'Skip unless you are deeply exploring AI tool integration',
    prerequisites: ['tool-calling-basics'],
    whatYouLearn: [
      'What the Model Context Protocol (MCP) is and why it was created',
      'How skills and plugins extend AI capabilities',
      'The difference between plugins, tools, and skills',
      'What MCP means for the future of AI connectivity',
    ],
  },
  {
    id: 'mod-019',
    slug: 'multimodal-ai',
    phaseSlug: 'phase-8-advanced-ai',
    title: 'Multimodal AI',
    description:
      'Explore AI that works with images, voice, video, and documents — not just text.',
    order: 19,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '🎨',
    tags: ['multimodal', 'images', 'voice', 'video', 'ocr'],
    lessonSlugs: ['images-and-ai', 'voice-and-video-ai'],
    isOptional: false,
    prerequisites: ['chatbots-in-depth'],
    whatYouLearn: [
      'What multimodal AI means and which tools support it',
      'Image generation, analysis, and editing with AI',
      'Voice and audio AI: transcription, synthesis, and voice assistants',
      'Practical multimodal workflows for everyday tasks',
    ],
  },
  {
    id: 'mod-020',
    slug: 'local-vs-cloud-ai',
    phaseSlug: 'phase-8-advanced-ai',
    title: 'Local AI vs Cloud AI',
    description:
      'Understand when to run AI on your own machine versus using cloud services — and what trade-offs come with each.',
    order: 20,
    difficulty: 'intermediate',
    estimatedHours: 2,
    icon: '☁️',
    tags: ['local-ai', 'cloud-ai', 'privacy', 'open-weights', 'ollama'],
    lessonSlugs: ['local-ai-options'],
    isOptional: true,
    skipLabel: 'Skip if privacy-first local AI is not a priority for you right now',
    prerequisites: ['privacy-and-data'],
    whatYouLearn: [
      'Why someone would run AI locally instead of using cloud services',
      'Tools like Ollama, LM Studio, and open-weights models',
      'The real trade-offs: capability, privacy, cost, and complexity',
      'Who should consider local AI and when',
    ],
  },
  // ── Phase 9: Capstone ──────────────────────────────────────────────────────
  {
    id: 'mod-021',
    slug: 'personal-ai-stack',
    phaseSlug: 'phase-9-capstone',
    title: 'Your Personal AI Stack',
    description:
      'Design your own combination of AI tools and workflows tailored to your work, life, and goals.',
    order: 21,
    difficulty: 'beginner',
    estimatedHours: 2,
    icon: '🎒',
    tags: ['personal-toolkit', 'ai-stack', 'workflow-design', 'capstone'],
    lessonSlugs: ['building-your-ai-stack'],
    isOptional: false,
    prerequisites: ['automation-basics'],
    whatYouLearn: [
      'How to evaluate AI tools for your specific needs',
      'Building a personal AI toolkit that fits your work',
      'Avoiding tool overload and staying focused',
      'A framework for reviewing and updating your stack over time',
    ],
  },
  {
    id: 'mod-022',
    slug: 'staying-current',
    phaseSlug: 'phase-9-capstone',
    title: 'Staying Current with AI',
    description:
      'AI moves fast. Learn how to stay informed without feeling overwhelmed — and build a sustainable learning habit.',
    order: 22,
    difficulty: 'beginner',
    estimatedHours: 1,
    icon: '📡',
    tags: ['learning-mindset', 'staying-current', 'ai-news', 'habits'],
    lessonSlugs: ['staying-current-in-ai'],
    isOptional: false,
    prerequisites: ['personal-ai-stack'],
    whatYouLearn: [
      'The best sources for staying current with AI (without overwhelm)',
      'How to filter signal from noise in AI news',
      'Building a sustainable AI learning habit',
      'The confident mindset for navigating a fast-moving field',
    ],
  },
];

export function getModuleBySlug(slug: string): Module | undefined {
  return modules.find((m) => m.slug === slug);
}

export function getModulesByPhase(phaseSlug: string): Module[] {
  return modules
    .filter((m) => m.phaseSlug === phaseSlug)
    .sort((a, b) => a.order - b.order);
}
