import type { PlanWeek } from '@/types';

export const weeklyPlan: PlanWeek[] = [
  {
    id: 'week-01',
    week: 1,
    title: 'Getting Your AI Bearings',
    focus: 'foundations',
    description:
      'Your first week is about building a solid mental model of what AI is, why it matters now, and getting hands-on with at least one AI tool. No deep theory — just get oriented.',
    goals: [
      'Understand the difference between AI, ML, and Generative AI',
      'Sign up and try ChatGPT or Claude',
      'Have at least 3 real conversations with an AI tool',
      'Learn what a prompt is and write your first intentional one',
    ],
    moduleSlugs: ['what-is-ai'],
    lessonSlugs: ['ai-vs-ml-vs-generative-ai', 'how-llms-work-simply'],
    tools: ['ChatGPT', 'Claude'],
    tip: 'Don\'t overthink it. Just start talking to an AI like you\'d talk to a knowledgeable friend. Ask it to explain something you\'ve been curious about.',
  },
  {
    id: 'week-02',
    week: 2,
    title: 'AI Tools Landscape',
    focus: 'tools',
    description:
      'In week 2, you\'ll survey the most useful AI tools available right now and understand which tool to reach for and when. You\'ll also do your first tool comparison.',
    goals: [
      'Know the major AI chatbots and their key differences',
      'Try at least two different AI tools for the same task',
      'Understand pricing tiers and what free gets you',
      'Identify 3 tasks in your own work where AI could help',
    ],
    moduleSlugs: ['ai-tools-overview'],
    tools: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity'],
    tip: 'Use Perplexity.ai for anything that needs a factual answer with sources. It dramatically reduces hallucination risk.',
  },
  {
    id: 'week-03',
    week: 3,
    title: 'Mastering Prompts',
    focus: 'prompting',
    description:
      'The biggest skill jump in week 3. Learning to write excellent prompts is the single most valuable AI skill for non-technical users. This week is hands-on.',
    goals: [
      'Learn the CRTF prompt framework (Context, Role, Task, Format)',
      'Practice iterative prompting on real tasks',
      'Build a personal prompt library with 5 templates',
      'Understand what causes bad AI outputs and how to fix them',
    ],
    moduleSlugs: ['prompting-basics'],
    lessonSlugs: ['anatomy-of-a-good-prompt', 'prompt-patterns'],
    tools: ['ChatGPT', 'Claude'],
    tip: "Keep a 'prompt journal' this week — save every prompt that worked really well. You're building a personal AI toolkit.",
  },
  {
    id: 'week-04',
    week: 4,
    title: 'Tokens, Context & How AI Thinks',
    focus: 'foundations',
    description: 'Understand the mechanics that explain AI behavior: tokens, context windows, and temperature. These concepts make everything else click.',
    goals: [
      'Understand what tokens are and why they matter for limits and cost',
      'Know your way around context windows and their practical implications',
      'Understand why AI gives different answers to the same question',
      'Apply this knowledge to prompt more effectively',
    ],
    moduleSlugs: ['understanding-llms'],
    lessonSlugs: ['tokens-explained', 'context-window-deep-dive'],
    tools: ['ChatGPT', 'Claude'],
    tip: "Test context window limits intentionally — paste a very long document and see what happens as you add more messages.",
  },
  {
    id: 'week-05',
    week: 5,
    title: 'Hallucination & Accuracy',
    focus: 'foundations',
    description: 'Build the critical-thinking habits that keep AI use safe. Understand hallucination deeply and develop a verification instinct.',
    goals: [
      'Understand why hallucination is fundamental, not a fixable bug',
      'Learn to spot the types of hallucination that are hardest to catch',
      'Build your own output evaluation habit using the SIFT framework',
      'Identify 3 task categories where you will always verify AI output',
    ],
    moduleSlugs: ['hallucinations-and-accuracy'],
    lessonSlugs: ['ai-hallucination-deep-dive', 'evaluating-ai-output'],
    tools: ['Perplexity', 'ChatGPT'],
    tip: 'Ask AI a question you already know the answer to. Then deliberately ask it about something obscure. Compare how it handles certainty vs uncertainty.',
  },
  {
    id: 'week-06',
    week: 6,
    title: 'Deep Dive: The Tools You Use',
    focus: 'tools',
    description: 'Go beyond the surface features of the AI tools you use every day. Understand what each excels at and build a smarter tool-selection habit.',
    goals: [
      'Learn ChatGPT features most users miss (Custom GPTs, Memory, Canvas)',
      'Understand when Claude outperforms ChatGPT and vice versa',
      'Build a personal task-to-tool map for your most common tasks',
      'Cancel any AI subscription you are not getting value from',
    ],
    moduleSlugs: ['chatbots-in-depth'],
    lessonSlugs: ['chatgpt-guide', 'model-comparison'],
    tools: ['ChatGPT', 'Claude', 'Gemini'],
    tip: 'Set up one Custom GPT this week — even a simple one with your name, role, and preferred response style. Notice how much context setup it saves.',
  },
  {
    id: 'week-07',
    week: 7,
    title: 'Advanced Prompting',
    focus: 'prompting',
    description: 'Level up your prompting with chain-of-thought reasoning, few-shot examples, and chained prompt workflows.',
    goals: [
      'Use chain-of-thought prompting on a real complex decision or analysis',
      'Build a few-shot prompt template for a recurring task',
      'Chain 3+ prompts together to complete a multi-step task',
      'Document your top 10 prompts in a reusable library',
    ],
    moduleSlugs: ['advanced-prompting', 'ai-workflows'],
    lessonSlugs: ['chain-of-thought-prompting', 'few-shot-prompting', 'building-your-first-workflow'],
    tools: ['Claude', 'ChatGPT'],
    tip: "Try 'think step by step' on a problem you've struggled with before. Compare the quality of reasoning to your first-try prompt.",
  },
  {
    id: 'week-08',
    week: 8,
    title: 'Automation Fundamentals',
    focus: 'automation',
    description: 'Start automating real tasks with AI. Move from manual AI use to recurring automated workflows.',
    goals: [
      'Identify your top 3 automation candidates from your actual weekly work',
      'Build your first Zapier or Make automation with an AI step',
      'Automate one real recurring task completely',
      'Measure time saved after one week',
    ],
    moduleSlugs: ['automation-basics'],
    lessonSlugs: ['what-is-ai-automation', 'no-code-automation-tools'],
    tools: ['Zapier', 'Make', 'ChatGPT API or Claude'],
    tip: 'The best first automation is the task you hate most because it is repetitive and mindless. That is where time saved feels the most rewarding.',
  },
  {
    id: 'week-09',
    week: 9,
    title: 'AI Agents',
    focus: 'agents',
    description: 'Understand AI agents deeply, try an agent-based tool, and decide where agents fit in your workflow.',
    goals: [
      'Understand the agent loop: plan → act → observe → repeat',
      'Try Perplexity Deep Research or another agent-based tool',
      'Identify 2 real tasks in your life where an agent could help',
      'Understand and articulate the safety concerns around agents',
    ],
    moduleSlugs: ['agents-introduction'],
    lessonSlugs: ['what-are-agents', 'how-agents-work'],
    tools: ['Perplexity (Deep Research)', 'Claude Projects', 'ChatGPT tasks'],
    tip: 'Start with a research agent task, not an action agent. Research agents are lower-risk and great for learning how agents work.',
  },
  {
    id: 'week-10',
    week: 10,
    title: 'Safety & Privacy',
    focus: 'review',
    description: 'Step back from capability building and focus on safe, responsible AI use. Audit your habits and close any security gaps.',
    goals: [
      'Audit your AI tool privacy settings and enable opt-outs where available',
      'Identify any sensitive data you have accidentally shared with AI',
      'Build a personal AI data policy (what you will and will not share)',
      'Review all AI output in your actual work from the last 2 weeks critically',
    ],
    moduleSlugs: ['safety-and-limitations', 'privacy-and-data'],
    lessonSlugs: ['ai-limitations', 'critical-evaluation', 'protecting-your-data'],
    tools: ['All tools you currently use'],
    tip: 'Check the privacy settings of every AI tool you use. Most people have never opened them. It takes 5 minutes and gives you real peace of mind.',
  },
  {
    id: 'week-11',
    week: 11,
    title: 'RAG, Memory & Advanced Systems',
    focus: 'advanced',
    description: 'Understand the advanced technology that powers the most capable AI workflows — RAG, embeddings, MCP, and local AI.',
    goals: [
      'Understand RAG conceptually and try a RAG-enabled tool (Notion AI, Copilot)',
      'Understand what embeddings are and why they matter',
      'Learn what MCP is and why it will matter for AI integrations',
      'Evaluate whether local AI makes sense for your privacy needs',
    ],
    moduleSlugs: ['rag-and-memory', 'embeddings-and-vectors', 'mcp-and-skills', 'local-vs-cloud-ai'],
    lessonSlugs: ['rag-explained', 'embeddings-simply', 'what-is-mcp', 'local-ai-options'],
    tools: ['Claude Projects', 'Notion AI', 'Ollama (optional)'],
    tip: 'Try asking Claude Projects a question about a document you uploaded. That experience makes RAG click instantly better than any explanation.',
  },
  {
    id: 'week-12',
    week: 12,
    title: 'Build Your AI Life',
    focus: 'workflows',
    description: 'Pull everything together. Design your personal AI stack, build sustainable habits, and graduate as a confident, effective AI user.',
    goals: [
      'Define your personal AI stack: 2-3 core tools with clear use cases',
      'Review all automations you built in week 8 — refine or expand one',
      'Build a 15-minute weekly AI review habit',
      'Set up one way to stay current: newsletter, YouTube, or community',
    ],
    moduleSlugs: ['personal-ai-stack', 'staying-current'],
    lessonSlugs: ['building-your-ai-stack', 'staying-current-in-ai'],
    tools: ['Your chosen core AI stack'],
    tip: 'Write down the 3 biggest changes AI has made to your workflow since week 1. That list is your evidence to share with colleagues, managers, or your future self.',
  },
];

export function getWeek(week: number): PlanWeek | undefined {
  return weeklyPlan.find((w) => w.week === week);
}
