import type { MiniProject } from '@/types';

export const projects: MiniProject[] = [
  {
    id: 'proj-001',
    slug: 'personal-knowledge-base',
    title: 'Build Your Personal AI Knowledge Base',
    description:
      'Use an AI chatbot to summarize and organize notes from articles, videos, and meetings into a searchable personal knowledge system.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['productivity', 'knowledge-management', 'summarization'],
    skills: ['Prompting', 'Iterative refinement', 'Summarization'],
    tools: ['ChatGPT or Claude', 'Notion or Obsidian (optional)'],
    steps: [
      'Choose 5 articles, videos, or notes from the past month that you wish you had retained better',
      'For each, paste the content into an AI chatbot and prompt: "Summarize this into: 1 key idea, 3 main points, 1 actionable takeaway. Use bullet points."',
      'Ask the AI to identify themes across all 5 summaries',
      'Create a simple document (Notion, Google Doc, flat text) with your summaries organized by theme',
      'Add one entry per week going forward',
    ],
    expectedOutput:
      'A structured notes document with 5 AI-summarized entries organized by theme, demonstrating your ability to use AI for learning retention.',
    bonusChallenges: [
      'Ask the AI to identify knowledge gaps based on your summaries',
      'Create a "reading list" prompt that suggests related topics',
      'Set up a weekly template prompt for consistent formatting',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'what-ai-can-and-cannot-do'],
  },
  {
    id: 'proj-002',
    slug: 'ai-writing-workflow',
    title: 'Design Your AI Writing Workflow',
    description:
      'Build a repeatable AI-assisted writing process for one type of document you write regularly — emails, reports, posts, or proposals.',
    difficulty: 'beginner',
    estimatedHours: 3,
    tags: ['writing', 'workflows', 'prompting', 'productivity'],
    skills: ['Prompt engineering', 'Workflow design', 'Editing with AI'],
    tools: ['ChatGPT or Claude'],
    steps: [
      'Pick one document type you write often (e.g., weekly update email, client proposal, LinkedIn post)',
      'Write down the steps you currently go through manually',
      'For each step, experiment with an AI prompt that speeds it up',
      'Document your best prompts for: first draft, editing, tone adjustment, subject line options',
      'Time yourself doing it the old way vs the AI-assisted way',
    ],
    expectedOutput:
      'A documented workflow with 3-5 reusable prompt templates for your chosen document type, plus a time comparison.',
    bonusChallenges: [
      'Build a "system prompt" that encodes your personal writing style and use it every time',
      'Create a version for a second document type',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'prompt-patterns'],
  },
  {
    id: 'proj-003',
    slug: 'ai-research-assistant',
    title: 'Use AI as a Research Assistant',
    description:
      'Research a topic you genuinely need to understand using AI tools — combining Perplexity for verified facts and Claude for synthesis.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['research', 'fact-checking', 'synthesis', 'critical-thinking'],
    skills: ['Research prompting', 'Source evaluation', 'AI synthesis'],
    tools: ['Perplexity (for sourced facts)', 'Claude or ChatGPT (for synthesis)'],
    steps: [
      'Pick a real topic you actually need to understand (work challenge, purchase decision, health topic)',
      'Use Perplexity to get a sourced overview — note which claims have strong citations',
      'Use Claude to ask "What are the most common misconceptions about [topic]?"',
      'Ask ChatGPT to explain it like you are [your background] and create a simple summary',
      'Identify one thing no AI got right or complete — verify it with a primary source',
    ],
    expectedOutput:
      'A 1-page summary of your topic that combines AI-assisted research with your own critical evaluation of the sources.',
    bonusChallenges: [
      'Compare the answers from three different AI tools on the same question',
      'Try to get the AI to give you contradictory statements to understand hallucination range',
    ],
    relatedLessons: ['what-ai-can-and-cannot-do', 'how-llms-work-simply'],
  },
  {
    id: 'proj-004',
    slug: 'meeting-notes-automation',
    title: 'Automate Your Meeting Notes',
    description: 'Build a repeatable workflow that turns raw meeting transcripts or notes into clean, structured summaries with action items.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['productivity', 'automation', 'meetings', 'writing'],
    skills: ['Prompt engineering', 'Output formatting', 'Template design'],
    tools: ['Claude or ChatGPT', 'Notion or Google Docs (optional)'],
    steps: [
      'Take raw notes from your next real meeting (bullet scrawl, transcript, or recording-to-text)',
      'Paste them into Claude with this prompt: "Convert these raw notes into: 1) Context (1 sentence), 2) Key decisions (bullets), 3) Action items (Owner: Task by Date), 4) Open questions"',
      'Refine the output — add any context the AI missed, remove anything incorrect',
      'Save that prompt as a Custom GPT instruction or a reusable template',
      'Use it for 3 consecutive meetings and measure how much time it saves',
    ],
    expectedOutput: 'A reusable meeting notes template prompt and 3 formatted meeting summaries ready to share.',
    bonusChallenges: [
      'Automate the workflow with Zapier: transcript arrives → AI formats → pushed to Notion',
      'Ask the AI to also suggest what to discuss in the NEXT meeting based on current open questions',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'building-your-first-workflow'],
  },
  {
    id: 'proj-005',
    slug: 'product-comparison',
    title: 'Product Comparison with AI',
    description: 'Use AI to research, compare, and recommend between two products — and learn the limits of what AI knows.',
    difficulty: 'beginner',
    estimatedHours: 1.5,
    tags: ['research', 'decision-making', 'fact-checking'],
    skills: ['Research prompting', 'Structured comparison', 'Hallucination detection'],
    tools: ['Perplexity', 'Claude or ChatGPT'],
    steps: [
      'Choose two real products you are considering buying (or have recently compared)',
      'Use Perplexity to get a sourced overview of each product',
      'Use Claude to write a structured comparison: "Compare [A] vs [B] for someone who [your use case]. Format as a table with pros/cons per category."',
      'Identify 2-3 specific claims that need checking — verify them via the manufacturer site or a review site',
      'Ask: "What questions should I ask a salesperson that AI cannot answer?"',
    ],
    expectedOutput: 'A verified product comparison document plus a list of questions that require human expertise.',
    bonusChallenges: [
      'Compare the AI recommendation against a human expert review',
      'Ask AI to steelman the product it did NOT recommend',
    ],
    relatedLessons: ['ai-for-research', 'ai-hallucination-deep-dive'],
  },
  {
    id: 'proj-006',
    slug: 'personal-weekly-planner',
    title: 'AI-Assisted Weekly Planner',
    description: 'Use AI to help you plan your week more intelligently — prioritizing tasks, blocking time, and anticipating blockers.',
    difficulty: 'beginner',
    estimatedHours: 1,
    tags: ['productivity', 'planning', 'time-management'],
    skills: ['Planning prompts', 'Prioritization', 'Workflow design'],
    tools: ['ChatGPT or Claude'],
    steps: [
      'Write a brain dump of everything you need to do next week (no filtering)',
      'Paste into AI: "Here is my task list. Group by: urgent+important, important-not-urgent, delegate/defer. Flag anything unrealistic given 5 working days."',
      'Ask: "Given these tasks and a 40-hour week, can you create a rough daily schedule?"',
      'Review and adjust — AI will not know your real constraints',
      'Use this as your Monday morning planning ritual for 4 weeks',
    ],
    expectedOutput: 'A structured weekly plan with prioritized tasks, time blocks, and flagged risks.',
    bonusChallenges: [
      'At week end, review how the AI plan matched reality — what did it get wrong?',
      'Build a prompt that includes your energy levels by time-of-day for better scheduling',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'what-is-ai-automation'],
  },
  {
    id: 'proj-007',
    slug: 'study-notes-generator',
    title: 'Generate Study Notes from Any Material',
    description: 'Use AI to transform textbooks, papers, podcasts (transcribed), or lecture notes into high-quality study material.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['learning', 'education', 'summarization', 'notes'],
    skills: ['Summarization', 'Question generation', 'Spaced repetition design'],
    tools: ['Claude (best for long documents)', 'ChatGPT'],
    steps: [
      'Choose a chapter or section you need to learn (paste or upload it)',
      'Prompt 1: "Summarize this material into: key concepts (bullet), important definitions, and 3 things I absolutely must remember"',
      'Prompt 2: "Generate 10 quiz questions from this content — mix multiple choice and short answer"',
      'Prompt 3: "Create a one-page cheat sheet with the most important information formatted for quick review"',
      'Test yourself with the quiz questions before looking at answers',
    ],
    expectedOutput: 'A study pack: concept summary, quiz questions, and a one-page reference cheat sheet.',
    bonusChallenges: [
      'Ask AI to create an analogy that maps this material to something you already know well',
      'Have AI generate "common misconceptions" for the topic to pre-empt mistakes',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'ai-for-research'],
  },
  {
    id: 'proj-008',
    slug: 'email-response-templates',
    title: 'Build an Email Response Library',
    description: 'Create a library of AI-crafted email templates for your most common email types — so you reply faster and more professionally.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['writing', 'email', 'templates', 'productivity'],
    skills: ['Role-play prompting', 'Tone adjustment', 'Template design'],
    tools: ['Claude or ChatGPT'],
    steps: [
      'List your 5 most common email types (e.g. declining a meeting, following up on a proposal, handling a complaint)',
      'For each type, write a base prompt: "Act as a professional communicator. Write a [type] email that is [tone]. Include: [key elements]. Keep it under 150 words."',
      'Generate 2-3 variations per email type with different tones',
      'Edit each template to match your actual voice and add your specific details',
      'Save these as reusable snippets in your email client or a doc',
    ],
    expectedOutput: 'A library of 10-15 polished email templates ready to use with minimal editing.',
    bonusChallenges: [
      'Build a system prompt that encodes your full writing style and generates everything in your voice',
      'Add a "difficult conversation" template for giving critical feedback professionally',
    ],
    relatedLessons: ['prompt-patterns', 'anatomy-of-a-good-prompt'],
  },
  {
    id: 'proj-009',
    slug: 'presentation-outline-builder',
    title: 'Build a Presentation Outline with AI',
    description: 'Use AI to rapidly scaffold a compelling presentation structure — then refine it into something genuinely compelling.',
    difficulty: 'beginner',
    estimatedHours: 1.5,
    tags: ['presentations', 'writing', 'structure', 'brainstorming'],
    skills: ['Structuring prompts', 'Narrative design', 'Iteration'],
    tools: ['ChatGPT or Claude'],
    steps: [
      'Define: topic, audience, goal, and time limit for your presentation',
      'Prompt: "Create a presentation outline for [topic] aimed at [audience]. Goal: [what you want them to do or believe after]. Time: [X] minutes. Include: hook, 3 key sections, supporting points per section, and a clear call to action."',
      'Ask for 3 alternative opening hooks',
      'Ask: "What objections might this audience have? How should I address them?"',
      'Build out one section in full with slide-level notes',
    ],
    expectedOutput: 'A complete presentation outline with alternative hooks, objection handling, and one fully developed section.',
    bonusChallenges: [
      'Ask AI to roleplay as a skeptical audience member and challenge the argument',
      'Have AI suggest the 3 most impactful visuals for the presentation',
    ],
    relatedLessons: ['chain-of-thought-prompting', 'prompt-patterns'],
  },
  {
    id: 'proj-010',
    slug: 'travel-planner-workflow',
    title: 'Build a Travel Planner Workflow',
    description: 'Use AI to plan a trip — itinerary, logistics, packing list, and contingency plans — and evaluate where AI shines vs falls short.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['productivity', 'planning', 'research', 'workflow'],
    skills: ['Multi-turn prompting', 'Research synthesis', 'Output templating'],
    tools: ['Perplexity (research)', 'Claude (planning)'],
    steps: [
      'Choose a real upcoming trip or a hypothetical destination',
      'Use Perplexity: "Top 10 things to do in [destination] for [type of traveler] in [season]"',
      'Use Claude: "Build me a day-by-day itinerary for 5 days in [destination] including: morning/afternoon/evening slots, transit notes, and meal options per day"',
      'Ask: "What are the most common mistakes tourists make in [destination]?"',
      'Ask: "Generate a packing list for [destination] in [season] for a [duration] trip"',
    ],
    expectedOutput: 'A complete trip plan with itinerary, packing list, and local tips, ready to use or refine.',
    bonusChallenges: [
      'Ask AI to build a contingency plan: "If it rains on day 2, what are indoor alternatives?"',
      'Compare Perplexity and ChatGPT recommendations for the same destination',
    ],
    relatedLessons: ['ai-for-research', 'choosing-the-right-tool'],
  },
  {
    id: 'proj-011',
    slug: 'prompt-testing-experiment',
    title: 'Prompt Testing Experiment',
    description: 'Systematically test how different prompt structures affect AI output quality — and build your personal prompt design instincts.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['prompting', 'experimentation', 'evaluation'],
    skills: ['A/B testing', 'Output evaluation', 'Prompt engineering'],
    tools: ['ChatGPT or Claude'],
    steps: [
      'Choose one task you use AI for regularly',
      'Write 4 versions of the prompt: vague, basic, CRTF framework, chain-of-thought',
      'Run all 4 on the same task using the same model and temperature',
      'Score each output on: accuracy, completeness, format quality, and tone (1-5 per criterion)',
      'Document which prompt produced the best result and WHY',
    ],
    expectedOutput: 'A documented prompt testing report with scored outputs and a thesis about what made the best prompt work.',
    bonusChallenges: [
      'Test the same prompts on two different models (e.g. Claude vs ChatGPT) and compare results',
      'Test with and without a few-shot example to see the impact',
    ],
    relatedLessons: ['anatomy-of-a-good-prompt', 'few-shot-prompting', 'chain-of-thought-prompting'],
  },
  {
    id: 'proj-012',
    slug: 'hallucination-hunt',
    title: 'The Hallucination Hunt',
    description: 'Deliberately probe AI for hallucinations on a topic you know well — and build a sharper intuition for catching them.',
    difficulty: 'intermediate',
    estimatedHours: 1.5,
    tags: ['hallucination', 'critical-thinking', 'evaluation'],
    skills: ['Fact verification', 'Hallucination pattern recognition', 'Critical evaluation'],
    tools: ['ChatGPT or Claude', 'Perplexity (for verification)'],
    steps: [
      'Choose a topic you know well — your industry, a hobby, a city you know deeply',
      'Ask AI 10 specific factual questions on that topic',
      'Record every answer before looking anything up',
      'Verify each answer against a reliable source',
      'Document: which type of facts had the most errors? What patterns do you notice?',
    ],
    expectedOutput: 'A hallucination audit with score, error patterns identified, and personal rules for when to verify AI output.',
    bonusChallenges: [
      'Compare hallucination rates between two different models on the same questions',
      'Test Perplexity vs ChatGPT — does citations reduce error rate?',
    ],
    relatedLessons: ['ai-hallucination-deep-dive', 'evaluating-ai-output'],
  },
  {
    id: 'proj-013',
    slug: 'ai-writing-style-analysis',
    title: 'Teach AI Your Writing Style',
    description: "Create a system prompt that captures your personal writing style so AI produces text that sounds like you, not like generic AI.",
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['writing', 'style', 'system-prompt', 'personalization'],
    skills: ['Style analysis', 'System prompt design', 'Voice preservation'],
    tools: ['Claude or ChatGPT'],
    steps: [
      'Collect 5 samples of your best writing (emails, posts, documents)',
      'Ask AI: "Analyze the writing style in these samples and describe it in detail: sentence length, vocabulary level, tone, structure, and distinctive patterns"',
      'Use that analysis to write a system prompt that instructs AI to match your style',
      'Test it by asking AI to draft a new email or post in your style',
      'Refine the system prompt based on where the style misses',
    ],
    expectedOutput: 'A personal writing style system prompt and 3 examples of AI-generated content that sound authentically like you.',
    bonusChallenges: [
      'Save this as a Custom GPT for instant access',
      'Try giving the same style prompt to two different models and compare',
    ],
    relatedLessons: ['prompt-patterns', 'chatgpt-guide'],
  },
  {
    id: 'proj-014',
    slug: 'no-code-automation-build',
    title: 'Build a No-Code AI Automation',
    description: 'Build a real, working automation that uses AI to handle a recurring task — without writing a single line of code.',
    difficulty: 'intermediate',
    estimatedHours: 3,
    tags: ['automation', 'no-code', 'zapier', 'productivity'],
    skills: ['Automation design', 'AI step integration', 'Workflow testing'],
    tools: ['Zapier (free tier)', 'Gmail or Notion', 'ChatGPT or Claude API (or Zapier AI steps)'],
    steps: [
      'Identify a real recurring task: email triage, weekly report generation, form response handling',
      'Map out the workflow: trigger → AI step → action',
      'In Zapier, create a new Zap with your trigger (e.g. new email with specific label)',
      'Add an AI step (Zapier has built-in AI actions) to summarize, classify, or transform the content',
      'Add the output action (e.g. create Notion page, send Slack message, add to spreadsheet)',
      'Test with 5 real examples and refine the AI prompt',
    ],
    expectedOutput: 'A live, working automation that handles a real task with zero manual effort after setup.',
    bonusChallenges: [
      'Add a second condition: if AI classifies as "urgent", also send a Slack alert',
      'Measure time saved over one month',
    ],
    relatedLessons: ['no-code-automation-tools', 'what-is-ai-automation'],
  },
  {
    id: 'proj-015',
    slug: 'agent-research-task',
    title: 'Run a Deep Research Agent Task',
    description: 'Use an AI agent (Perplexity Deep Research or ChatGPT Tasks) to conduct a multi-step research task autonomously and evaluate the results.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['agents', 'research', 'evaluation'],
    skills: ['Agent task design', 'Output evaluation', 'Source verification'],
    tools: ['Perplexity Deep Research', 'ChatGPT with computer use (optional)'],
    steps: [
      'Define a research question that requires 5+ sources (e.g. "What are the main approaches to no-code AI automation in 2025?")',
      'Submit it to Perplexity Deep Research or a similar agent tool',
      'Let it run autonomously — do not interrupt',
      'When it finishes, evaluate: did it answer the question? Were sources legitimate? Were any claims suspicious?',
      'Fact-check 5 specific claims from the report',
    ],
    expectedOutput: 'A research report plus your own evaluation of agent quality, source quality, and hallucination rate.',
    bonusChallenges: [
      'Have the agent research the same topic as a previous manual research task — compare quality and time',
      'Ask the agent to evaluate its own confidence in each section',
    ],
    relatedLessons: ['what-are-agents', 'ai-for-research'],
  },
  {
    id: 'proj-016',
    slug: 'rag-knowledge-base-design',
    title: 'Design a RAG-Based Personal Notes System',
    description: 'Conceptually design (and optionally build with a tool like Notion AI) a personal knowledge base that uses RAG to make your notes searchable by AI.',
    difficulty: 'intermediate',
    estimatedHours: 3,
    tags: ['rag', 'knowledge-management', 'design', 'productivity'],
    skills: ['System design', 'RAG understanding', 'Knowledge architecture'],
    tools: ['Notion AI', 'Claude Projects (for experimentation)', 'Paper/diagrams'],
    steps: [
      'Map your current note-taking: where do notes live, what types of content, what do you search for most?',
      'Design the ideal structure: what categories? what metadata? what should be searchable?',
      'Try Claude Projects: upload 10 of your existing notes/docs and ask questions about them',
      'Note what worked well and what was missing',
      'Write a 1-page design doc: how you would structure a personal RAG system for your work',
    ],
    expectedOutput: 'A design document for your personal AI knowledge base plus a Claude Projects experiment demonstrating RAG in action.',
    bonusChallenges: [
      'Try building it in Notion AI: organize your notes and use Notion AI to ask questions across them',
      'Test: what happens when you ask a question for which there is no matching document?',
    ],
    relatedLessons: ['rag-explained', 'embeddings-simply'],
  },
  {
    id: 'proj-017',
    slug: 'privacy-audit',
    title: 'AI Privacy Audit',
    description: 'Conduct a systematic audit of your AI tool data practices and implement concrete privacy protections.',
    difficulty: 'beginner',
    estimatedHours: 1.5,
    tags: ['privacy', 'security', 'audit', 'safety'],
    skills: ['Privacy settings navigation', 'Data risk assessment', 'Policy design'],
    tools: ['All AI tools you currently use'],
    steps: [
      'List every AI tool you use regularly',
      'For each tool: find and check the privacy settings (training data opt-out, data retention)',
      'Review your last 30 days of AI conversations — did you share anything you should not have?',
      'Write your personal AI data policy: "I will / will not share [categories] with AI"',
      'Implement all privacy settings you found in step 2',
    ],
    expectedOutput: 'A personal AI data policy document and all privacy settings opted-out where available.',
    bonusChallenges: [
      'Research your company\'s AI policy — does one exist? Does it cover the tools you use?',
      'Test running a sensitive discussion on a local AI model instead of cloud',
    ],
    relatedLessons: ['protecting-your-data', 'local-ai-options'],
  },
  {
    id: 'proj-018',
    slug: 'compare-three-tools',
    title: 'Three-Tool Comparison Challenge',
    description: 'Give the same prompt to three different AI tools and document the differences in quality, style, and accuracy.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['tool-comparison', 'evaluation', 'research'],
    skills: ['Cross-tool evaluation', 'Comparative analysis', 'Bias detection'],
    tools: ['ChatGPT', 'Claude', 'Gemini or Perplexity'],
    steps: [
      'Choose one complex, open-ended question relevant to your work',
      'Submit the exact same prompt to ChatGPT, Claude, and one other tool',
      'Compare outputs on: length, structure, tone, specific claims, and nuance',
      'Identify 2-3 specific factual claims and verify them',
      'Write a brief assessment: which tool produced the best output for THIS task, and why?',
    ],
    expectedOutput: 'A comparison report with noted strengths and weaknesses per tool for your specific use case.',
    bonusChallenges: [
      'Repeat with a creative task and a factual task — see if rankings change',
      'Submit the same question a second time to the same model and note consistency',
    ],
    relatedLessons: ['model-comparison', 'evaluating-ai-output'],
  },
  {
    id: 'proj-019',
    slug: 'ai-for-code-beginners',
    title: 'AI as a Coding Assistant (No Experience Needed)',
    description: 'Use AI to automate a simple data task — even if you have never written code — by letting AI write and explain the code for you.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['coding', 'automation', 'data', 'no-code'],
    skills: ['Coding prompt design', 'Code explanation reading', 'Debugging with AI'],
    tools: ['ChatGPT (Code Interpreter)', 'Claude'],
    steps: [
      'Choose a data task you currently do manually: cleaning a spreadsheet, counting occurrences, formatting a list',
      'Prompt: "Write Python code that [task]. I am not a developer — explain each line in simple terms."',
      'In ChatGPT with Code Interpreter: upload a sample file and ask it to run the code',
      'If there is an error, paste the error back and ask: "This error occurred. Fix it and explain what went wrong"',
      'Reflect: what took longer, understanding the code or doing the task manually?',
    ],
    expectedOutput: 'A working code snippet that automates one data task, with your own annotations explaining what it does.',
    bonusChallenges: [
      'Ask AI to turn the code into a function you could reuse',
      'Have AI review its own code for edge cases or errors',
    ],
    relatedLessons: ['chatgpt-guide', 'what-is-ai-automation'],
  },
  {
    id: 'proj-020',
    slug: 'local-ai-setup',
    title: 'Set Up and Test a Local AI Model',
    description: 'Install Ollama and run an open-weights AI model entirely on your own machine — no internet required.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['local-ai', 'privacy', 'ollama', 'setup'],
    skills: ['Local AI setup', 'Model evaluation', 'Privacy trade-off assessment'],
    tools: ['Ollama (free)', 'LM Studio (free)', 'Your computer'],
    steps: [
      'Go to ollama.com and follow the installation instructions for your OS',
      'Run: "ollama pull llama3.2" to download a compact model',
      'Start a conversation: "ollama run llama3.2"',
      'Ask it the same 5 questions you regularly ask ChatGPT',
      'Note: quality differences, speed differences, and what it cannot do that cloud AI can',
    ],
    expectedOutput: 'A running local AI setup and a personal assessment: when would you use local AI vs cloud AI?',
    bonusChallenges: [
      'Install Open WebUI for a ChatGPT-like interface to your local Ollama models',
      'Try a larger model if your hardware supports it (llama3.1:8b or 13b)',
    ],
    relatedLessons: ['local-ai-options', 'protecting-your-data'],
  },
  {
    id: 'proj-021',
    slug: 'personal-ai-stack-design',
    title: 'Design Your Personal AI Stack',
    description: 'Map out and commit to a personal AI toolkit that covers your core use cases without tool overload.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['strategy', 'toolkit', 'planning', 'capstone'],
    skills: ['Strategic tool selection', 'Workflow mapping', 'Habit design'],
    tools: ['Paper or digital notes', 'Any AI tool for research'],
    steps: [
      'List your top 5-7 recurring tasks where AI could help',
      'For each task, identify the best tool based on what you learned in this course',
      'Check: are you picking more than 3 tools? If so, trim — pick the most versatile',
      'Write a 1-page "AI toolkit card": tool name, use case, and your default prompt template',
      'Commit to using this stack for 90 days before evaluating',
    ],
    expectedOutput: 'Your personal AI stack document: 2-3 tools with mapped use cases and default prompts.',
    bonusChallenges: [
      'Share your stack with one colleague and help them build theirs',
      'Set a calendar reminder for 90 days out to review and revise',
    ],
    relatedLessons: ['building-your-ai-stack', 'choosing-the-right-tool'],
  },
  {
    id: 'proj-022',
    slug: 'ai-document-summarizer',
    title: 'Summarize a Long Document',
    description: 'Use AI to extract the key insights from a long document — report, paper, or policy — in minutes instead of hours.',
    difficulty: 'beginner',
    estimatedHours: 1,
    tags: ['summarization', 'reading', 'productivity', 'research'],
    skills: ['Document analysis prompts', 'Progressive summarization', 'Output structuring'],
    tools: ['Claude (best for long docs)', 'ChatGPT'],
    steps: [
      'Choose a document you have been meaning to read but have not had time for (PDF, article, report)',
      'Upload to Claude and prompt: "Summarize this document: 1) Main argument in one sentence, 2) 5 key points, 3) Key data or findings, 4) Conclusions and recommendations"',
      'Ask: "What are the strongest and weakest arguments in this document?"',
      'Ask: "What important questions does this document NOT answer?"',
      'Rate the summary against a quick skim of the original document',
    ],
    expectedOutput: 'A structured summary of a real document you needed to understand, plus your accuracy rating.',
    bonusChallenges: [
      'Compare summaries from two documents and ask AI to synthesize the key themes across both',
      'Ask AI to identify any contradictions between the document and what you already know about the topic',
    ],
    relatedLessons: ['chatgpt-guide', 'context-window-deep-dive'],
  },
  {
    id: 'proj-023',
    slug: 'ai-workflow-map',
    title: 'Map an AI Agent Workflow',
    description: 'Design a multi-step agent workflow on paper — without building it — to understand how agentic tasks are structured.',
    difficulty: 'intermediate',
    estimatedHours: 1.5,
    tags: ['agents', 'workflow-design', 'planning'],
    skills: ['System thinking', 'Agent workflow design', 'Tool identification'],
    tools: ['Paper, whiteboard, or Miro/FigJam'],
    steps: [
      'Choose a multi-step task you currently do manually (e.g. researching a company, processing applications, weekly status report)',
      'Map the current manual process as a flowchart',
      'For each step, ask: could an AI agent do this? What tool would it use?',
      'Redesign the workflow with AI agent steps: specify trigger, tools, decision points, human checkpoints',
      'Identify where human review is essential vs where AI can operate autonomously',
    ],
    expectedOutput: 'A before-and-after workflow diagram showing manual vs AI-agent-assisted process.',
    bonusChallenges: [
      'Estimate time savings if the agent workflow were implemented',
      'Identify the highest-risk step and design a guardrail for it',
    ],
    relatedLessons: ['what-are-agents', 'how-agents-work', 'building-your-first-workflow'],
  },
  {
    id: 'proj-024',
    slug: 'mcp-exploration',
    title: 'Explore MCP in Action',
    description: 'Connect Claude Desktop to a local MCP server and experience firsthand what AI can do with real tool access.',
    difficulty: 'intermediate',
    estimatedHours: 2,
    tags: ['mcp', 'agents', 'integration', 'hands-on'],
    skills: ['MCP setup', 'Tool-augmented AI', 'Evaluation'],
    tools: ['Claude Desktop (free)', 'A file system MCP server or GitHub MCP server'],
    steps: [
      'Download and install Claude Desktop from claude.ai/download',
      'Follow the Claude Desktop MCP setup guide to add the Filesystem MCP server',
      'Allow Claude to access a non-sensitive folder on your computer',
      'Ask Claude: "What files are in my documents folder?" and see it use the tool',
      'Try a more complex task: "Read my notes file and summarize it"',
    ],
    expectedOutput: 'A working MCP connection and your own assessment of what this enables for future AI workflows.',
    bonusChallenges: [
      'Set up the GitHub MCP server and ask Claude to review your (or a public) repository',
      'Document 3 real use cases where MCP would save you significant time',
    ],
    relatedLessons: ['what-is-mcp', 'how-agents-work'],
  },
  {
    id: 'proj-025',
    slug: 'course-capstone',
    title: 'Course Capstone: Your AI Transformation Story',
    description: 'Reflect on and document how you have changed as an AI user over this course — then design your next 90 days.',
    difficulty: 'beginner',
    estimatedHours: 2,
    tags: ['capstone', 'reflection', 'planning', 'growth'],
    skills: ['Self-assessment', 'Strategic planning', 'Documentation'],
    tools: ['Any AI tool for structure assistance', 'Your notes from previous projects'],
    steps: [
      'Reflect on week 1 vs now: list 5 specific things you can do with AI that you could not before',
      'Review all the projects you completed: which delivered the most value? Which would you use ongoing?',
      'Identify the 3 most impactful AI habits you have developed',
      'Design your "next 90 days" AI roadmap: what do you want to build, automate, or explore next?',
      'Write a one-paragraph "AI literacy statement" — what you know, what you use, and what you value',
    ],
    expectedOutput: "Your AI transformation story + a 90-day roadmap for what you'll build next.",
    bonusChallenges: [
      'Share your transformation with a colleague and help them start their own AI learning journey',
      'Contribute to this course by documenting a new project idea based on your real work',
    ],
    relatedLessons: ['building-your-ai-stack', 'staying-current-in-ai'],
  },
];

export function getProjectBySlug(slug: string): MiniProject | undefined {
  return projects.find((p) => p.slug === slug);
}
