import type { FAQ } from '@/types';

export const faqs: FAQ[] = [
  {
    id: 'faq-001',
    question: 'Do I need to know how to code to use AI tools?',
    answer: 'No. Most modern AI tools — ChatGPT, Claude, Gemini, Perplexity — are designed for everyday users with no technical background. You just type in natural language. That said, learning basic prompting techniques (covered in this course) will dramatically improve your results. Coding knowledge only becomes useful if you want to build AI-powered apps or automate complex workflows via APIs.',
    category: 'getting-started',
    tags: ['no-code', 'beginners', 'skills-required'],
  },
  {
    id: 'faq-002',
    question: 'Which AI tool should I start with?',
    answer: "For most beginners, start with either ChatGPT (free tier is excellent) or Claude. Both handle a wide range of everyday tasks. ChatGPT has the largest ecosystem of integrations. Claude is often preferred for longer documents and careful writing. Try both for a week and see which feels more natural. You'll probably end up using multiple tools for different purposes.",
    category: 'tools',
    tags: ['chatgpt', 'claude', 'getting-started', 'beginners'],
    relatedLessons: ['chatbot-landscape', 'choosing-the-right-tool'],
  },
  {
    id: 'faq-003',
    question: 'Why does AI sometimes give wrong answers?',
    answer: "AI chatbots work by predicting the next most likely word in a sequence — they don't actually look things up or verify facts in real time. They can produce confident-sounding text even when it's wrong. This is called 'hallucination.' The best defense is to treat AI output as a smart first draft that needs verification for important facts, always ask follow-up questions, and use tools like Perplexity that show you their sources.",
    category: 'concepts',
    tags: ['hallucination', 'accuracy', 'fact-checking'],
    relatedLessons: ['how-llms-work-simply', 'ai-hallucination-deep-dive'],
  },
  {
    id: 'faq-004',
    question: 'Is my data safe when I use AI tools?',
    answer: "It depends on the tool and how you use it. For ChatGPT, Claude, and Gemini — your conversations may be used to improve models unless you opt out. You should never paste sensitive personal data (SSNs, passwords, medical records, confidential business information) into any AI chatbot. For business use, check if an enterprise tier is available with stronger data privacy guarantees. For truly sensitive work, local AI models are an option.",
    category: 'safety',
    tags: ['privacy', 'data', 'enterprise', 'sensitive-data'],
    relatedLessons: ['protecting-your-data'],
  },
  {
    id: 'faq-005',
    question: 'Will AI replace my job?',
    answer: "AI will change most jobs — but 'replace' is too blunt a word. For most knowledge workers, AI automates repetitive parts of work and amplifies what they can produce. The practical approach: learn which parts of your work can be augmented by AI, use that to do more in less time, and focus on uniquely human skills — judgment, relationships, creativity, and domain expertise.",
    category: 'career',
    tags: ['jobs', 'future-of-work', 'automation'],
  },
  {
    id: 'faq-006',
    question: 'Do I need math or a technical background?',
    answer: "Not at all. This course is explicitly designed for people without a technical background. You will learn conceptual understanding of how AI works — enough to use it well and talk about it confidently — without any mathematics, statistics, or programming. The most important skill is learning to communicate clearly with AI tools through well-crafted prompts.",
    category: 'getting-started',
    tags: ['math', 'technical', 'background', 'beginners'],
  },
  {
    id: 'faq-007',
    question: 'What is RAG in simple words?',
    answer: "RAG stands for Retrieval-Augmented Generation. In simple terms: before answering your question, the AI first searches a library of documents to find the most relevant information, then uses that information to answer. This makes AI much more accurate on specific topics and allows it to answer questions about your own documents. Tools like Perplexity, Notion AI, and Microsoft 365 Copilot all use RAG under the hood.",
    category: 'concepts',
    tags: ['rag', 'retrieval', 'knowledge-base'],
    relatedLessons: ['rag-explained'],
  },
  {
    id: 'faq-008',
    question: 'What is MCP?',
    answer: "MCP (Model Context Protocol) is an open standard introduced by Anthropic that lets AI models connect to external tools, files, databases, and services in a standardized way. Think of it like USB for AI — instead of every AI tool needing a custom integration with every service, MCP creates one standard connector that works everywhere. It's becoming the foundation for AI agents that can interact with your real tools.",
    category: 'concepts',
    tags: ['mcp', 'protocol', 'integration', 'agents'],
    relatedLessons: ['what-is-mcp'],
  },
  {
    id: 'faq-009',
    question: 'What are "skills" in AI?',
    answer: "In AI, 'skills' refer to packaged capabilities that an AI agent can invoke — like searching the web, reading your calendar, or sending an email. The term is used most commonly in Microsoft Copilot. Skills, plugins, and tools all describe variations of the same concept: giving an AI model the ability to call an external function or service. When you see 'AI skills', think 'capabilities the AI can use beyond just generating text'.",
    category: 'concepts',
    tags: ['skills', 'plugins', 'tools', 'agents'],
    relatedLessons: ['ai-skills-explained', 'what-is-tool-calling'],
  },
  {
    id: 'faq-010',
    question: 'What is the difference between a plugin and a tool?',
    answer: "A tool is a specific function an AI can call — like 'run a web search' or 'execute this code'. A plugin is a packaged of tools bundled together — for example, a ChatGPT plugin for a specific service. The terminology varies by platform: OpenAI uses 'tools' and 'GPT actions', Microsoft uses 'skills', and Anthropic's Claude uses 'MCP servers'. They all describe the same concept: giving AI access to external capabilities.",
    category: 'concepts',
    tags: ['plugins', 'tools', 'terminology'],
  },
  {
    id: 'faq-011',
    question: 'Do I need to learn about agents right now?',
    answer: "Not necessarily. For most everyday AI tasks — writing, research, summarization, brainstorming — you can get enormous value from a well-crafted prompt without touching agents. Agents become relevant when you want to automate multi-step tasks that span multiple tools or data sources. Start with prompting fundamentals, build some simple workflows, and then explore agents when you find yourself wanting more automation power.",
    category: 'learning-path',
    tags: ['agents', 'priority', 'learning-path'],
    relatedLessons: ['what-are-agents'],
  },
  {
    id: 'faq-012',
    question: 'How do I protect private data when using AI?',
    answer: "Three practical rules: 1) Never paste passwords, credentials, SSNs, medical data, or confidential business documents into a free consumer AI tool. 2) Enable the privacy settings in every tool you use — most have 'opt out of training' options. 3) For genuinely sensitive work, use enterprise-tier tools (which don't train on your data) or local AI models (which never send data to the cloud). Review your settings today — it takes 5 minutes.",
    category: 'safety',
    tags: ['privacy', 'data', 'security'],
    relatedLessons: ['protecting-your-data'],
  },
  {
    id: 'faq-013',
    question: 'Should I pay for an AI tool?',
    answer: "The free tiers of ChatGPT, Claude, and Gemini are genuinely excellent starting points. Pay for a tool only when you hit a specific limitation that is blocking real work — like needing longer context windows, image generation, or faster responses. ChatGPT Plus ($20/mo) and Claude Pro ($20/mo) are the most popular paid upgrades and both deliver strong value for regular users. Start free, upgrade when the free tier consistently frustrates you.",
    category: 'tools',
    tags: ['pricing', 'free-vs-paid', 'value'],
  },
  {
    id: 'faq-014',
    question: 'How do I keep up with new AI terms without feeling lost?',
    answer: "Focus on building a strong conceptual foundation (which this course does) rather than memorizing every new term. When you encounter an unfamiliar term, look it up in the glossary here, or ask AI itself to explain it simply. Subscribe to one good AI newsletter — The Rundown or TLDR AI — for a weekly 5-minute overview. Accept that the vocabulary will keep expanding and let curiosity drive your learning rather than anxiety about keeping up.",
    category: 'learning-path',
    tags: ['terminology', 'staying-current', 'mindset'],
    relatedLessons: ['staying-current-in-ai'],
  },
  {
    id: 'faq-015',
    question: 'Can AI replace my thinking?',
    answer: "It can replace parts of it — and that is both an opportunity and a risk. AI can handle a lot of the mechanical work of thinking: drafting, structuring, and generating options. But judgment, values, context, and domain expertise are yours. The risk is over-relying on AI and letting those muscles atrophy. The opportunity is offloading the routine parts so you can apply your judgment where it matters most. Use AI to amplify your thinking, not replace it.",
    category: 'concepts',
    tags: ['thinking', 'judgment', 'over-reliance'],
  },
  {
    id: 'faq-016',
    question: 'What is a context window and why should I care?',
    answer: "The context window is the total amount of text an AI model can 'see' and process in a single session — including your messages, documents you've uploaded, and the AI's previous responses. When it fills up, older content is dropped and the AI may seem to 'forget' things. Practically: if you're working on a long project, summarize progress and start a new chat periodically. For document analysis, choose Claude (200K context) over smaller models.",
    category: 'concepts',
    tags: ['context-window', 'memory', 'tokens'],
    relatedLessons: ['context-window-deep-dive'],
  },
  {
    id: 'faq-017',
    question: 'Is there a free way to try local AI?',
    answer: "Yes. Ollama is a free, open-source tool that lets you run AI models (like Llama 3, Mistral, and Gemma) directly on your computer. It takes about 10 minutes to set up on Mac, Windows, or Linux. For a more polished experience, LM Studio gives you a ChatGPT-like interface on your local machine, also free. The trade-off: local models are less capable than frontier cloud models, but they run with complete privacy and no internet required.",
    category: 'tools',
    tags: ['local-ai', 'free', 'privacy', 'ollama'],
    relatedLessons: ['local-ai-options'],
  },
  {
    id: 'faq-018',
    question: 'How accurate is AI for medical, legal, or financial questions?',
    answer: "AI can give you useful background information and help you understand concepts in any of these fields. But it should never replace a qualified professional for important decisions. AI can hallucinate specific medical dosages, misstate legal precedents, and give financial advice that ignores your personal situation. Use AI to understand a topic and prepare smarter questions for the actual expert — not to bypass the expert.",
    category: 'safety',
    tags: ['medical', 'legal', 'financial', 'professional-advice'],
  },
  {
    id: 'faq-019',
    question: 'What is the difference between ChatGPT and GPT-4?',
    answer: "ChatGPT is the product — the chat interface you use at chat.openai.com. GPT-4 (and GPT-4o) is the underlying AI model that powers it. OpenAI makes the models (GPT-3.5, GPT-4, GPT-4o, o1) and runs ChatGPT as the consumer product that lets you use those models. Other companies also build products on top of OpenAI's models via the API. So 'ChatGPT' and 'GPT-4o' are related but not the same thing.",
    category: 'concepts',
    tags: ['chatgpt', 'gpt-4', 'models', 'openai'],
  },
  {
    id: 'faq-020',
    question: 'How is Claude different from ChatGPT?',
    answer: "Claude (by Anthropic) and ChatGPT (by OpenAI) are both capable AI assistants but have distinct strengths. Claude tends to excel at longer-form analysis, very long documents (200K context), and careful, nuanced writing with fewer hallucinations. ChatGPT has a larger ecosystem of integrations, better image generation (DALL-E), and the widest plugin/tool ecosystem. Both are excellent starting points — try both for a week and you'll quickly develop a preference based on your work style.",
    category: 'tools',
    tags: ['claude', 'chatgpt', 'comparison'],
    relatedLessons: ['model-comparison'],
  },
  {
    id: 'faq-021',
    question: 'What does "training cutoff" mean?',
    answer: "AI models are trained on a large dataset of text up to a specific date — the training cutoff. After that date, the model has no knowledge of new events, research, or developments. For example, a model with a training cutoff of January 2025 does not know about anything that happened after that date unless you tell it or use a tool with web search. This is why AI tools with real-time search (like Perplexity or ChatGPT with browsing) are better for current events and recent information.",
    category: 'concepts',
    tags: ['training-cutoff', 'knowledge-cutoff', 'real-time'],
  },
  {
    id: 'faq-022',
    question: 'Can I use AI for my work without my employer finding out?',
    answer: "This is an important question. Many companies now have AI use policies, and using AI tools with company data could violate those policies or confidentiality agreements — even if you're trying to be helpful. Best practice: check your company's AI policy first. Never paste confidential data into consumer AI tools. If your company doesn't have a policy yet, advocate for a clear one. When in doubt, use AI only on non-confidential parts of your work.",
    category: 'safety',
    tags: ['workplace', 'confidentiality', 'policy'],
  },
  {
    id: 'faq-023',
    question: 'What is the difference between open-source and closed-source AI models?',
    answer: "Closed-source (or proprietary) models — like GPT-4, Claude, and Gemini — are run by companies, accessible via API or their products, and the model weights are kept private. Open-weights models (often called 'open-source') — like Meta's Llama, Mistral, and Gemma — have their model parameters released publicly, allowing anyone to download, run, and fine-tune them. Open models offer privacy and customization but are typically less capable than the frontier closed models.",
    category: 'concepts',
    tags: ['open-source', 'closed-source', 'llama', 'open-weights'],
  },
  {
    id: 'faq-024',
    question: 'What does "hallucination" look like in real use?',
    answer: "Hallucination is when AI confidently states something false. It might invent a book title and author that sound real but do not exist. It might state a statistic as \"48%\" when the real number was \"38%\". It might give you a URL that looks legitimate but leads nowhere. It might attribute a quote to the wrong person. The tricky ones are subtle — not outright fabrications but small distortions of real facts. Always check specific claims, dates, numbers, and citations.",
    category: 'concepts',
    tags: ['hallucination', 'examples', 'fact-checking'],
    relatedLessons: ['ai-hallucination-deep-dive'],
  },
  {
    id: 'faq-025',
    question: 'How long does it take to become proficient with AI tools?',
    answer: "You can become a confident, effective AI user faster than you think. Most people reach a useful level of proficiency — writing good prompts, knowing which tool to use, and having reliable verification habits — within 4-8 weeks of active use. This 12-week course is designed to take you from beginner to genuinely skilled. The key is not passive reading but active practice: use AI every day, on real tasks, and iterate based on what works.",
    category: 'learning-path',
    tags: ['time', 'learning', 'progress'],
  },
];

export function getFAQsByCategory(category: string): FAQ[] {
  return faqs.filter((f) => f.category === category);
}
