import type { ToolEntry } from '@/types';

export const tools: ToolEntry[] = [
  {
    id: 'tool-001',
    slug: 'chatgpt',
    name: 'ChatGPT',
    description:
      'OpenAI\'s general-purpose AI assistant. The most widely used AI chatbot, capable of writing, coding, analysis, and more. GPT-4o is the flagship model.',
    category: 'chatbot',
    url: 'https://chatgpt.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'General writing and editing',
      'Research and summarization',
      'Coding assistance',
      'Brainstorming and ideation',
      'Learning new concepts',
    ],
    limitations: [
      'Free tier uses slower model',
      'Knowledge cutoff (may not know recent events without search)',
      'Can hallucinate confidently',
      'Some tasks require the paid plan',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Code interpreter', supported: true },
      { name: 'Image generation', supported: 'partial', note: 'Paid plan only' },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: 'Custom GPTs', supported: true },
    ],
    logoEmoji: '🤖',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-002',
    slug: 'claude',
    name: 'Claude',
    description:
      'Anthropic\'s AI assistant known for nuanced writing, long-context processing, and thoughtful, careful responses. Excellent for long documents.',
    category: 'chatbot',
    url: 'https://claude.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Long document analysis and editing',
      'Nuanced writing with good style',
      'Thoughtful, careful reasoning',
      'Analyzing PDFs and documents',
      'Coding and debugging',
    ],
    limitations: [
      'Image generation not available',
      'Free tier has usage limits',
      'Less popular ecosystem of integrations than ChatGPT',
    ],
    features: [
      { name: 'Web search', supported: 'partial', note: 'Via tools feature' },
      { name: 'Code interpreter', supported: true },
      { name: 'Image generation', supported: false },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: '200K context window', supported: true },
    ],
    logoEmoji: '🧡',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-003',
    slug: 'gemini',
    name: 'Gemini',
    description:
      'Google\'s AI assistant with deep integration into Google Workspace. Strong multimodal capabilities and real-time web access.',
    category: 'chatbot',
    url: 'https://gemini.google.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Google Workspace users (Gmail, Docs, Drive)',
      'Multimodal tasks (images + text)',
      'Real-time web search',
      'Analysis of YouTube videos',
    ],
    limitations: [
      'Deep Google ecosystem lock-in',
      'Some features require paid Gemini Advanced',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Google Workspace integration', supported: true },
      { name: 'Image generation', supported: true },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: 'Multimodal (image input)', supported: true },
    ],
    logoEmoji: '🔵',
    isPopular: true,
  },
  {
    id: 'tool-004',
    slug: 'midjourney',
    name: 'Midjourney',
    description:
      'The most popular AI image generation tool, known for its distinctive artistic quality and photorealism. Accessed via Discord.',
    category: 'image-generation',
    url: 'https://midjourney.com',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'High-quality artistic images',
      'Marketing and creative visuals',
      'Concept art and illustrations',
      'Photorealistic images',
    ],
    limitations: [
      'No free tier',
      'Requires Discord account',
      'All generated images are public on free/basic plans',
    ],
    logoEmoji: '🎨',
    isPopular: true,
  },
  {
    id: 'tool-005',
    slug: 'perplexity',
    name: 'Perplexity',
    description:
      'An AI-powered research and search tool that provides sourced, cited answers to questions in real time.',
    category: 'search',
    url: 'https://perplexity.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Research with cited sources',
      'Current events and factual lookups',
      'Learning about new topics quickly',
      'Reducing hallucination risk',
    ],
    limitations: [
      'Less conversational than pure chatbots',
      'Advanced features require Pro plan',
    ],
    logoEmoji: '🔍',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-006',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer integrated into VS Code and other editors — suggests code, explains code, and writes tests.',
    category: 'coding',
    url: 'https://github.com/features/copilot',
    pricing: 'paid',
    difficulty: 'intermediate',
    bestFor: [
      'Code completion and generation',
      'Explaining unfamiliar code',
      'Writing unit tests',
      'Refactoring existing code',
    ],
    limitations: [
      'Requires paid subscription (free tier limited)',
      'Best results with context-rich codebases',
      'May suggest outdated patterns for rapidly evolving frameworks',
    ],
    features: [
      { name: 'IDE integration', supported: true },
      { name: 'Chat in editor', supported: true },
      { name: 'Multi-file editing', supported: true, note: 'Copilot Workspace' },
      { name: 'Free tier', supported: 'partial', note: 'Limited free usage' },
    ],
    logoEmoji: '🐙',
    isPopular: true,
  },
  {
    id: 'tool-007',
    slug: 'cursor',
    name: 'Cursor',
    description: 'An AI-native code editor built on VS Code that provides deep AI integration for editing, debugging, and building.',
    category: 'coding',
    url: 'https://cursor.sh',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'AI-first coding experience',
      'Multi-file understanding and edits',
      'Codebase Q&A',
      'Building with AI from scratch',
    ],
    limitations: [
      'Subscription required for heavy use',
      'Overkill for occasional coding tasks',
    ],
    features: [
      { name: 'Multi-file editing', supported: true },
      { name: 'Codebase context', supported: true },
      { name: 'Multiple models', supported: true, note: 'GPT-4, Claude, etc.' },
      { name: 'Free tier', supported: true },
    ],
    logoEmoji: '⚡',
    isPopular: true,
  },
  {
    id: 'tool-008',
    slug: 'zapier',
    name: 'Zapier',
    description: 'The most popular no-code automation platform — connect 7,000+ apps with AI-powered workflows.',
    category: 'automation',
    url: 'https://zapier.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Automating repetitive cross-app workflows',
      'Adding AI steps to workflows',
      'Trigger-based automations',
      'Non-technical users',
    ],
    limitations: [
      'Complex workflows can get expensive',
      'Less flexibility than code for edge cases',
      'AI steps require higher-tier plan',
    ],
    features: [
      { name: 'AI Actions (ChatGPT step)', supported: true },
      { name: 'No-code setup', supported: true },
      { name: '7,000+ app integrations', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited tasks/month' },
    ],
    logoEmoji: '⚡',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-009',
    slug: 'make',
    name: 'Make (formerly Integromat)',
    description: 'A powerful visual workflow automation platform with more flexibility than Zapier for complex multi-step flows.',
    category: 'automation',
    url: 'https://make.com',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'Complex multi-step automations',
      'Data transformation workflows',
      'More control than Zapier at lower cost',
    ],
    limitations: [
      'Steeper learning curve than Zapier',
      'Visual complexity increases with workflow complexity',
    ],
    features: [
      { name: 'Visual flow editor', supported: true },
      { name: 'AI module', supported: true },
      { name: 'Free tier', supported: true, note: '1,000 operations/month' },
      { name: 'Error handling', supported: true },
    ],
    logoEmoji: '🔧',
    isPopular: true,
  },
  {
    id: 'tool-010',
    slug: 'notion-ai',
    name: 'Notion AI',
    description: "AI built directly into Notion — draft, summarize, translate, and analyze inside your workspace.",
    category: 'productivity',
    url: 'https://notion.so/product/ai',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'Notion users who want AI in their workflow',
      'Drafting and editing documents',
      'Summarizing long pages',
      'Extracting action items from meeting notes',
    ],
    limitations: [
      'Requires active Notion subscription',
      'Less powerful than dedicated AI assistants for complex tasks',
    ],
    features: [
      { name: 'Inline AI writing', supported: true },
      { name: 'Summarize page', supported: true },
      { name: 'Translate', supported: true },
      { name: 'Database Q&A', supported: true },
    ],
    logoEmoji: '📝',
    isPopular: true,
  },
  {
    id: 'tool-011',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: "The leading AI voice generation platform — convert text to natural speech, clone voices, and create audio content.",
    category: 'voice',
    url: 'https://elevenlabs.io',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Creating voiceovers for videos',
      'Audiobook production',
      'Podcast content creation',
      'Voice cloning for personalized AI',
    ],
    limitations: [
      'Voice cloning raises ethical considerations',
      'Free tier limited to small monthly credit',
    ],
    features: [
      { name: 'Voice cloning', supported: true },
      { name: 'Multi-language', supported: true, note: '29+ languages' },
      { name: 'API access', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited monthly characters' },
    ],
    logoEmoji: '🎙️',
    isPopular: true,
  },
  {
    id: 'tool-012',
    slug: 'ollama',
    name: 'Ollama',
    description: "The easiest way to run open-weights AI models locally on your machine — no cloud, no data sharing.",
    category: 'local-ai',
    url: 'https://ollama.com',
    pricing: 'free',
    difficulty: 'intermediate',
    bestFor: [
      'Privacy-sensitive tasks (no cloud)',
      'Offline AI usage',
      'Testing and experimenting with open models',
      'Developers building local AI apps',
    ],
    limitations: [
      'Requires a capable computer (8+ GB RAM recommended)',
      'Models are smaller and less capable than frontier cloud models',
      'Command-line setup required',
    ],
    features: [
      { name: 'Completely free', supported: true },
      { name: 'No data sent to cloud', supported: true },
      { name: 'Dozens of models available', supported: true },
      { name: 'GUI not included', supported: false, note: 'Use with LM Studio for GUI' },
    ],
    logoEmoji: '🦙',
    isPopular: true,
  },
  {
    id: 'tool-013',
    slug: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: "Adobe's AI image and creative content generator — built for commercial use with licensed training data.",
    category: 'image-generation',
    url: 'https://firefly.adobe.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Commercially safe image generation',
      'Integration with Photoshop and Illustrator',
      'Generative fill and expand',
      'Creative professionals in the Adobe ecosystem',
    ],
    limitations: [
      'Less stylistically diverse than Midjourney',
      'Full features require Creative Cloud subscription',
    ],
    features: [
      { name: 'Commercial license safe', supported: true },
      { name: 'Photoshop integration', supported: true },
      { name: 'Text effects', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited generation credits' },
    ],
    logoEmoji: '🔥',
    isPopular: true,
  },
  {
    id: 'tool-014',
    slug: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    description: "Microsoft's AI assistant embedded across Windows, Office 365, Edge, and Bing — powered by GPT-4 and Bing search.",
    category: 'chatbot',
    url: 'https://copilot.microsoft.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Microsoft 365 users (Word, Excel, Outlook, Teams)',
      'Windows users wanting free GPT-4 access',
      'Enterprise users who need data compliance',
      'Web search augmented chat',
    ],
    limitations: [
      'Microsoft 365 Copilot features require expensive enterprise plan',
      'Interface less polished than ChatGPT for heavy users',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Free GPT-4 access', supported: true },
      { name: 'Office integration', supported: 'partial', note: 'Requires M365 Copilot add-on' },
      { name: 'Image generation (DALL-E)', supported: true },
    ],
    logoEmoji: '🪟',
    isPopular: true,
    isBeginnnerPick: true,
  },
];

export function getToolBySlug(slug: string): ToolEntry | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolEntry[] {
  return tools.filter((t) => t.category === category);
}

export function getBeginnerPicks(): ToolEntry[] {
  return tools.filter((t) => t.isBeginnnerPick);
}
