import type { ToolEntry } from '@/types';

export const tools: ToolEntry[] = [
  {
    id: 'tool-001',
    slug: 'chatgpt',
    name: 'ChatGPT',
    description:
      'OpenAI\'s general-purpose AI assistant. The most widely used AI chatbot, capable of writing, coding, analysis, and more. GPT-4o is the flagship model.',
    category: 'chatbot',
    url: 'https://chatgpt.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'General writing and editing',
      'Research and summarization',
      'Coding assistance',
      'Brainstorming and ideation',
      'Learning new concepts',
    ],
    limitations: [
      'Free tier uses slower model',
      'Knowledge cutoff (may not know recent events without search)',
      'Can hallucinate confidently',
      'Some tasks require the paid plan',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Code interpreter', supported: true },
      { name: 'Image generation', supported: 'partial', note: 'Paid plan only' },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: 'Custom GPTs', supported: true },
    ],
    logoEmoji: '🤖',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-002',
    slug: 'claude',
    name: 'Claude',
    description:
      'Anthropic\'s AI assistant known for nuanced writing, long-context processing, and thoughtful, careful responses. Excellent for long documents.',
    category: 'chatbot',
    url: 'https://claude.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Long document analysis and editing',
      'Nuanced writing with good style',
      'Thoughtful, careful reasoning',
      'Analyzing PDFs and documents',
      'Coding and debugging',
    ],
    limitations: [
      'Image generation not available',
      'Free tier has usage limits',
      'Less popular ecosystem of integrations than ChatGPT',
    ],
    features: [
      { name: 'Web search', supported: 'partial', note: 'Via tools feature' },
      { name: 'Code interpreter', supported: true },
      { name: 'Image generation', supported: false },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: '200K context window', supported: true },
    ],
    logoEmoji: '🧡',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-003',
    slug: 'gemini',
    name: 'Gemini',
    description:
      'Google\'s AI assistant with deep integration into Google Workspace. Strong multimodal capabilities and real-time web access.',
    category: 'chatbot',
    url: 'https://gemini.google.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Google Workspace users (Gmail, Docs, Drive)',
      'Multimodal tasks (images + text)',
      'Real-time web search',
      'Analysis of YouTube videos',
    ],
    limitations: [
      'Deep Google ecosystem lock-in',
      'Some features require paid Gemini Advanced',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Google Workspace integration', supported: true },
      { name: 'Image generation', supported: true },
      { name: 'File upload', supported: true },
      { name: 'API access', supported: true },
      { name: 'Multimodal (image input)', supported: true },
    ],
    logoEmoji: '🔵',
    isPopular: true,
  },
  {
    id: 'tool-004',
    slug: 'midjourney',
    name: 'Midjourney',
    description:
      'The most popular AI image generation tool, known for its distinctive artistic quality and photorealism. Accessed via Discord.',
    category: 'image-generation',
    url: 'https://midjourney.com',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'High-quality artistic images',
      'Marketing and creative visuals',
      'Concept art and illustrations',
      'Photorealistic images',
    ],
    limitations: [
      'No free tier',
      'Requires Discord account',
      'All generated images are public on free/basic plans',
    ],
    logoEmoji: '🎨',
    isPopular: true,
  },
  {
    id: 'tool-005',
    slug: 'perplexity',
    name: 'Perplexity',
    description:
      'An AI-powered research and search tool that provides sourced, cited answers to questions in real time.',
    category: 'search',
    url: 'https://perplexity.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Research with cited sources',
      'Current events and factual lookups',
      'Learning about new topics quickly',
      'Reducing hallucination risk',
    ],
    limitations: [
      'Less conversational than pure chatbots',
      'Advanced features require Pro plan',
    ],
    logoEmoji: '🔍',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-006',
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer integrated into VS Code and other editors — suggests code, explains code, and writes tests.',
    category: 'coding',
    url: 'https://github.com/features/copilot',
    pricing: 'paid',
    difficulty: 'intermediate',
    bestFor: [
      'Code completion and generation',
      'Explaining unfamiliar code',
      'Writing unit tests',
      'Refactoring existing code',
    ],
    limitations: [
      'Requires paid subscription (free tier limited)',
      'Best results with context-rich codebases',
      'May suggest outdated patterns for rapidly evolving frameworks',
    ],
    features: [
      { name: 'IDE integration', supported: true },
      { name: 'Chat in editor', supported: true },
      { name: 'Multi-file editing', supported: true, note: 'Copilot Workspace' },
      { name: 'Free tier', supported: 'partial', note: 'Limited free usage' },
    ],
    logoEmoji: '🐙',
    isPopular: true,
  },
  {
    id: 'tool-007',
    slug: 'cursor',
    name: 'Cursor',
    description: 'An AI-native code editor built on VS Code that provides deep AI integration for editing, debugging, and building.',
    category: 'coding',
    url: 'https://cursor.sh',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'AI-first coding experience',
      'Multi-file understanding and edits',
      'Codebase Q&A',
      'Building with AI from scratch',
    ],
    limitations: [
      'Subscription required for heavy use',
      'Overkill for occasional coding tasks',
    ],
    features: [
      { name: 'Multi-file editing', supported: true },
      { name: 'Codebase context', supported: true },
      { name: 'Multiple models', supported: true, note: 'GPT-4, Claude, etc.' },
      { name: 'Free tier', supported: true },
    ],
    logoEmoji: '⚡',
    isPopular: true,
  },
  {
    id: 'tool-008',
    slug: 'zapier',
    name: 'Zapier',
    description: 'The most popular no-code automation platform — connect 7,000+ apps with AI-powered workflows.',
    category: 'automation',
    url: 'https://zapier.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Automating repetitive cross-app workflows',
      'Adding AI steps to workflows',
      'Trigger-based automations',
      'Non-technical users',
    ],
    limitations: [
      'Complex workflows can get expensive',
      'Less flexibility than code for edge cases',
      'AI steps require higher-tier plan',
    ],
    features: [
      { name: 'AI Actions (ChatGPT step)', supported: true },
      { name: 'No-code setup', supported: true },
      { name: '7,000+ app integrations', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited tasks/month' },
    ],
    logoEmoji: '⚡',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-009',
    slug: 'make',
    name: 'Make (formerly Integromat)',
    description: 'A powerful visual workflow automation platform with more flexibility than Zapier for complex multi-step flows.',
    category: 'automation',
    url: 'https://make.com',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'Complex multi-step automations',
      'Data transformation workflows',
      'More control than Zapier at lower cost',
    ],
    limitations: [
      'Steeper learning curve than Zapier',
      'Visual complexity increases with workflow complexity',
    ],
    features: [
      { name: 'Visual flow editor', supported: true },
      { name: 'AI module', supported: true },
      { name: 'Free tier', supported: true, note: '1,000 operations/month' },
      { name: 'Error handling', supported: true },
    ],
    logoEmoji: '🔧',
    isPopular: true,
  },
  {
    id: 'tool-010',
    slug: 'notion-ai',
    name: 'Notion AI',
    description: "AI built directly into Notion — draft, summarize, translate, and analyze inside your workspace.",
    category: 'productivity',
    url: 'https://notion.so/product/ai',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'Notion users who want AI in their workflow',
      'Drafting and editing documents',
      'Summarizing long pages',
      'Extracting action items from meeting notes',
    ],
    limitations: [
      'Requires active Notion subscription',
      'Less powerful than dedicated AI assistants for complex tasks',
    ],
    features: [
      { name: 'Inline AI writing', supported: true },
      { name: 'Summarize page', supported: true },
      { name: 'Translate', supported: true },
      { name: 'Database Q&A', supported: true },
    ],
    logoEmoji: '📝',
    isPopular: true,
  },
  {
    id: 'tool-011',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: "The leading AI voice generation platform — convert text to natural speech, clone voices, and create audio content.",
    category: 'voice',
    url: 'https://elevenlabs.io',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Creating voiceovers for videos',
      'Audiobook production',
      'Podcast content creation',
      'Voice cloning for personalized AI',
    ],
    limitations: [
      'Voice cloning raises ethical considerations',
      'Free tier limited to small monthly credit',
    ],
    features: [
      { name: 'Voice cloning', supported: true },
      { name: 'Multi-language', supported: true, note: '29+ languages' },
      { name: 'API access', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited monthly characters' },
    ],
    logoEmoji: '🎙️',
    isPopular: true,
  },
  {
    id: 'tool-012',
    slug: 'ollama',
    name: 'Ollama',
    description: "The easiest way to run open-weights AI models locally on your machine — no cloud, no data sharing.",
    category: 'local-ai',
    url: 'https://ollama.com',
    pricing: 'free',
    difficulty: 'intermediate',
    bestFor: [
      'Privacy-sensitive tasks (no cloud)',
      'Offline AI usage',
      'Testing and experimenting with open models',
      'Developers building local AI apps',
    ],
    limitations: [
      'Requires a capable computer (8+ GB RAM recommended)',
      'Models are smaller and less capable than frontier cloud models',
      'Command-line setup required',
    ],
    features: [
      { name: 'Completely free', supported: true },
      { name: 'No data sent to cloud', supported: true },
      { name: 'Dozens of models available', supported: true },
      { name: 'GUI not included', supported: false, note: 'Use with LM Studio for GUI' },
    ],
    logoEmoji: '🦙',
    isPopular: true,
  },
  {
    id: 'tool-013',
    slug: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: "Adobe's AI image and creative content generator — built for commercial use with licensed training data.",
    category: 'image-generation',
    url: 'https://firefly.adobe.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Commercially safe image generation',
      'Integration with Photoshop and Illustrator',
      'Generative fill and expand',
      'Creative professionals in the Adobe ecosystem',
    ],
    limitations: [
      'Less stylistically diverse than Midjourney',
      'Full features require Creative Cloud subscription',
    ],
    features: [
      { name: 'Commercial license safe', supported: true },
      { name: 'Photoshop integration', supported: true },
      { name: 'Text effects', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited generation credits' },
    ],
    logoEmoji: '🔥',
    isPopular: true,
  },
  {
    id: 'tool-014',
    slug: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    description: "Microsoft's AI assistant embedded across Windows, Office 365, Edge, and Bing — powered by GPT-4 and Bing search.",
    category: 'chatbot',
    url: 'https://copilot.microsoft.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Microsoft 365 users (Word, Excel, Outlook, Teams)',
      'Windows users wanting free GPT-4 access',
      'Enterprise users who need data compliance',
      'Web search augmented chat',
    ],
    limitations: [
      'Microsoft 365 Copilot features require expensive enterprise plan',
      'Interface less polished than ChatGPT for heavy users',
    ],
    features: [
      { name: 'Web search', supported: true },
      { name: 'Free GPT-4 access', supported: true },
      { name: 'Office integration', supported: 'partial', note: 'Requires M365 Copilot add-on' },
      { name: 'Image generation (DALL-E)', supported: true },
    ],
    logoEmoji: '🪟',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-015',
    slug: 'dalle-3',
    name: 'DALL-E 3',
    description:
      'OpenAI\'s latest text-to-image model, integrated directly into ChatGPT. Generates highly detailed, accurate images from natural language prompts.',
    category: 'image-generation',
    url: 'https://openai.com/dall-e-3',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'Text-accurate image generation',
      'Marketing and ad visuals',
      'Users already on ChatGPT Plus',
      'Quick concept mockups',
    ],
    limitations: [
      'No free tier',
      'Less artistic control than Midjourney',
      'Fixed aspect ratios',
    ],
    features: [
      { name: 'ChatGPT integration', supported: true },
      { name: 'Text rendering in images', supported: true },
      { name: 'High prompt adherence', supported: true },
      { name: 'API access', supported: true, note: 'via OpenAI API' },
    ],
    logoEmoji: '🖼️',
    isPopular: true,
  },
  {
    id: 'tool-016',
    slug: 'canva-ai',
    name: 'Canva AI',
    description:
      'AI image generation and editing tools built into Canva\'s design platform — generate images, remove backgrounds, and more.',
    category: 'image-generation',
    url: 'https://canva.com/ai-image-generator',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Social media graphics and marketing',
      'Quick image edits without design skills',
      'Users already in the Canva ecosystem',
      'Templates + AI combination',
    ],
    limitations: [
      'Advanced image generation requires paid plan',
      'Less control than dedicated AI image tools',
    ],
    features: [
      { name: 'Text-to-image', supported: true },
      { name: 'Background remover', supported: true },
      { name: 'Template library', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited credits' },
    ],
    logoEmoji: '🎨',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-017',
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    description:
      'Open-source image generation model that runs locally or via cloud services. Highly customizable and free.',
    category: 'image-generation',
    url: 'https://stability.ai',
    pricing: 'open-source',
    difficulty: 'intermediate',
    bestFor: [
      'Privacy-focused image generation',
      'Fine-tuned model customization',
      'Running locally without cloud costs',
      'Developers integrating AI into apps',
    ],
    limitations: [
      'Hardware requirements for local use (GPU recommended)',
      'Steeper learning curve than web-based tools',
      'Quality varies by model and settings',
    ],
    features: [
      { name: 'Open-source', supported: true },
      { name: 'Runs locally', supported: true },
      { name: 'Custom model fine-tuning', supported: true },
      { name: 'Free', supported: true },
    ],
    logoEmoji: '🎨',
    isPopular: true,
  },
  {
    id: 'tool-018',
    slug: 'runwayml',
    name: 'RunwayML',
    description:
      'AI-powered video and image generation platform — text-to-video, image-to-video, green screen removal, and more.',
    category: 'video',
    url: 'https://runwayml.com',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'AI video generation and editing',
      'Creative professionals and filmmakers',
      'Image-to-video transformations',
      'Experimental AI art',
    ],
    limitations: [
      'Video generation is compute-heavy and costly',
      'Short clips only on free tier',
      'Requires some technical understanding for best results',
    ],
    features: [
      { name: 'Text-to-video', supported: true },
      { name: 'Image-to-video', supported: true },
      { name: 'Green screen (no background)', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited credits' },
    ],
    logoEmoji: '🎬',
    isPopular: true,
  },
  {
    id: 'tool-019',
    slug: 'synthesia',
    name: 'Synthesia',
    description:
      'Create professional AI avatar videos — type a script, pick an avatar, and generate a video in minutes without cameras or actors.',
    category: 'video',
    url: 'https://www.synthesia.io',
    pricing: 'paid',
    difficulty: 'beginner',
    bestFor: [
      'Corporate training videos',
      'Multilingual video content',
      'Quick spokesperson videos without filming',
      'Internal communications',
    ],
    limitations: [
      'No free tier (paid plans only)',
      'Avatar expressions can feel unnatural',
      'Limited customization of avatars',
    ],
    features: [
      { name: '140+ AI avatars', supported: true },
      { name: '120+ languages', supported: true },
      { name: 'Custom avatar', supported: 'partial', note: 'Enterprise plan' },
      { name: 'Video templates', supported: true },
    ],
    logoEmoji: '🎬',
    isPopular: true,
  },
  {
    id: 'tool-020',
    slug: 'heygen',
    name: 'HeyGen',
    description:
      'AI video platform that lets you create avatar-based videos, translate videos into other languages, and clone voices.',
    category: 'video',
    url: 'https://www.heygen.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Personalized video messages at scale',
      'Video translation and localization',
      'Marketing and sales videos',
      'AI avatar presentations',
    ],
    limitations: [
      'Free tier has watermark and time limits',
      'Avatar realism still improving',
      'Best results require good script writing',
    ],
    features: [
      { name: 'AI avatar videos', supported: true },
      { name: 'Video translation', supported: true },
      { name: 'Voice cloning', supported: true },
      { name: 'Free tier', supported: true, note: 'Watermarked, 1 min max' },
    ],
    logoEmoji: '🎬',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-021',
    slug: 'suno',
    name: 'Suno',
    description:
      'Create full AI-generated songs — vocals, instruments, and lyrics — from a simple text prompt. The leading AI music generation tool.',
    category: 'video',
    url: 'https://suno.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'AI-generated music and songs',
      'Content creators needing background music',
      'Experimenting with AI creativity',
      'Fun and entertainment',
    ],
    limitations: [
      'Free tier limited credits and commercial restrictions',
      'Lyrics and quality can be inconsistent',
      'Music ownership depends on plan',
    ],
    features: [
      { name: 'Text-to-music', supported: true },
      { name: 'Vocals generation', supported: true },
      { name: 'Multiple genres', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited daily credits' },
    ],
    logoEmoji: '🎵',
    isPopular: true,
  },
  {
    id: 'tool-022',
    slug: 'murf-ai',
    name: 'Murf AI',
    description:
      'AI voice generation platform for creating natural-sounding voiceovers from text — ideal for e-learning, marketing, and presentations.',
    category: 'voice',
    url: 'https://murf.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'E-learning voiceover narration',
      'Explainer videos and demos',
      'Podcast intro/outro generation',
      'Multilingual voice content',
    ],
    limitations: [
      'Voice quality slightly behind ElevenLabs',
      'Limited voice customization on lower plans',
    ],
    features: [
      { name: '120+ voices', supported: true },
      { name: '20+ languages', supported: true },
      { name: 'Voice customization', supported: 'partial', note: 'Pitch, speed control' },
      { name: 'Free tier', supported: true, note: '10 min generation' },
    ],
    logoEmoji: '🎙️',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-023',
    slug: 'playht',
    name: 'Play.ht',
    description:
      'AI voice generation platform with ultra-realistic voice cloning and a large library of voices for content creators.',
    category: 'voice',
    url: 'https://play.ht',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'Podcast and audiobook production',
      'Voice cloning for content creators',
      'Multilingual audio content',
      'API integration for apps',
    ],
    limitations: [
      'Voice cloning requires paid plan',
      'Can sound robotic on some voices',
    ],
    features: [
      { name: 'Voice cloning', supported: 'partial', note: 'Paid plans' },
      { name: '800+ voices', supported: true },
      { name: 'API access', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited word count' },
    ],
    logoEmoji: '🎙️',
    isPopular: true,
  },
  {
    id: 'tool-024',
    slug: 'grammarly',
    name: 'Grammarly',
    description:
      'AI writing assistant that checks grammar, spelling, tone, and clarity in real time — integrated across browsers and apps.',
    category: 'productivity',
    url: 'https://grammarly.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Grammar and spell checking',
      'Tone and clarity suggestions',
      'Non-native English speakers',
      'Professional email and document writing',
    ],
    limitations: [
      'Premium features require paid subscription',
      'Can be overly aggressive with suggestions',
      'Not ideal for creative or highly technical writing',
    ],
    features: [
      { name: 'Grammar/spell check', supported: true },
      { name: 'Tone detection', supported: 'partial', note: 'Premium' },
      { name: 'Plagiarism checker', supported: 'partial', note: 'Premium' },
      { name: 'Free tier', supported: true },
    ],
    logoEmoji: '📝',
    isPopular: true,
    isBeginnnerPick: true,
  },
  {
    id: 'tool-025',
    slug: 'jasper',
    name: 'Jasper',
    description:
      'AI writing and marketing content platform — generate blog posts, ad copy, and marketing content with brand-consistent tone.',
    category: 'productivity',
    url: 'https://jasper.ai',
    pricing: 'paid',
    difficulty: 'intermediate',
    bestFor: [
      'Marketing teams and content creators',
      'Brand-consistent AI writing',
      'Long-form blog posts and articles',
      'Ad copy and social media content',
    ],
    limitations: [
      'No free tier (paid plans start high)',
      'Best for marketing use cases, less for general writing',
      'Requires setup for brand voice',
    ],
    features: [
      { name: 'Brand voice customization', supported: true },
      { name: '50+ templates', supported: true },
      { name: 'SEO mode', supported: true },
      { name: 'Team collaboration', supported: true },
    ],
    logoEmoji: '📝',
    isPopular: true,
  },
  {
    id: 'tool-026',
    slug: 'copy-ai',
    name: 'Copy.ai',
    description:
      'AI copywriting tool for generating marketing copy, product descriptions, and short-form content at scale.',
    category: 'productivity',
    url: 'https://copy.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Short-form marketing copy',
      'Product descriptions and listings',
      'Social media captions',
      'Email subject lines',
    ],
    limitations: [
      'Long-form content quality lags behind dedicated tools',
      'Free tier heavily limited',
    ],
    features: [
      { name: '90+ copy templates', supported: true },
      { name: 'Free tier', supported: true, note: '2,000 words/month' },
      { name: 'Workflow automation', supported: 'partial', note: 'Paid plans' },
      { name: 'Multiple languages', supported: true },
    ],
    logoEmoji: '📝',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-027',
    slug: 'windsurf',
    name: 'Windsurf',
    description:
      'AI-powered IDE by Codeium — free AI code completion, chat, and inline suggestions across multiple editors.',
    category: 'coding',
    url: 'https://codeium.com/windsurf',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'Free AI code completion across editors',
      'Developers wanting a Copilot alternative',
      'Multi-language support',
      'Privacy-focused on-premise option',
    ],
    limitations: [
      'Newer tool with smaller community',
      'Some advanced features require paid plan',
      'Context awareness still evolving',
    ],
    features: [
      { name: 'Free tier', supported: true },
      { name: 'IDE integration', supported: true },
      { name: 'Multi-language support', supported: true },
      { name: 'Chat in editor', supported: true },
    ],
    logoEmoji: '🏄',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-028',
    slug: 'replit-ai',
    name: 'Replit AI',
    description:
      'AI coding assistant built into the Replit online IDE — generate, explain, and debug code in the browser with no setup.',
    category: 'coding',
    url: 'https://replit.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Beginners learning to code',
      'Quick prototyping in the browser',
      'No local setup required',
      'Collaborative coding with AI',
    ],
    limitations: [
      'Cloud IDE has performance limits',
      'Heavy use requires paid Replit plan',
      'Less suited for large enterprise codebases',
    ],
    features: [
      { name: 'In-browser IDE', supported: true },
      { name: 'AI code generation', supported: true },
      { name: 'Natural language to code', supported: true },
      { name: 'Free tier', supported: true },
    ],
    logoEmoji: '💻',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-029',
    slug: 'tabnine',
    name: 'Tabnine',
    description:
      'AI code completion tool that supports all major IDEs and languages — runs locally or in the cloud for privacy-sensitive teams.',
    category: 'coding',
    url: 'https://tabnine.com',
    pricing: 'freemium',
    difficulty: 'intermediate',
    bestFor: [
      'Privacy-focused code completion',
      'Teams needing self-hosted AI',
      'Wide IDE and language support',
      'On-premise deployments',
    ],
    limitations: [
      'Free tier limited to single-line suggestions',
      'Slightly behind Copilot in model capability',
      'Enterprise setup can be complex',
    ],
    features: [
      { name: 'Local model option', supported: true },
      { name: 'IDE integration', supported: true },
      { name: 'Multiple languages', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited' },
    ],
    logoEmoji: '💻',
    isPopular: true,
  },
  {
    id: 'tool-030',
    slug: 'you-com',
    name: 'You.com',
    description:
      'Privacy-focused AI search engine with multiple AI modes (Smart, Creative, Genius) and no ad-tracking.',
    category: 'search',
    url: 'https://you.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Privacy-focused AI search',
      'Multi-mode AI responses',
      'Quick answers with less tracking',
      'AI-powered browsing assistant',
    ],
    limitations: [
      'Smaller index than Google or Bing',
      'Some features require paid YouPro',
      'Less widely used than mainstream search engines',
    ],
    features: [
      { name: 'AI modes (Smart/Creative/Genius)', supported: true },
      { name: 'No ad tracking', supported: true },
      { name: 'Free tier', supported: true },
      { name: 'App integration', supported: true },
    ],
    logoEmoji: '🔍',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-031',
    slug: 'brave-search',
    name: 'Brave Search',
    description:
      'Privacy-first search engine with built-in AI summarization and answer generation — no tracking, no ads by default.',
    category: 'search',
    url: 'https://search.brave.com',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Privacy-first web search',
      'AI-summarized search results',
      'Users avoiding Google/Bing tracking',
      'Integrated AI Q&A on search results',
    ],
    limitations: [
      'AI summaries sometimes less detailed than Perplexity',
      'Smaller search index than Google',
    ],
    features: [
      { name: 'Privacy-first', supported: true },
      { name: 'AI summarization', supported: 'partial', note: 'Premium Brave Search AI' },
      { name: 'No ads by default', supported: true },
      { name: 'Free tier', supported: true },
    ],
    logoEmoji: '🔍',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-032',
    slug: 'consensus',
    name: 'Consensus',
    description:
      'AI-powered academic search engine that extracts findings from scientific papers and provides evidence-based answers.',
    category: 'search',
    url: 'https://consensus.app',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Academic and scientific research',
      'Evidence-based health and science answers',
      'Quick literature reviews',
      'Students and researchers',
    ],
    limitations: [
      'Limited to academic/scientific content',
      'Premium features are expensive',
      'Less useful for general web search',
    ],
    features: [
      { name: 'Academic paper search', supported: true },
      { name: 'Cited findings', supported: true },
      { name: 'Free tier', supported: true, note: 'Limited searches/month' },
      { name: 'Paper summary', supported: true },
    ],
    logoEmoji: '🔍',
    isPopular: true,
  },
  {
    id: 'tool-033',
    slug: 'huggingchat',
    name: 'HuggingChat',
    description:
      'Open-source AI chat interface from Hugging Face — free, no login required, powered by open models like Llama and Mistral.',
    category: 'chatbot',
    url: 'https://huggingface.co/chat',
    pricing: 'open-source',
    difficulty: 'beginner',
    bestFor: [
      'Free, open-access AI chat',
      'Experimenting with open models',
      'Users who want no-login access',
      'Developers testing open-source models',
    ],
    limitations: [
      'Quality varies by underlying model',
      'Less polished than ChatGPT or Claude',
      'Can be slower during peak times',
    ],
    features: [
      { name: 'No login required', supported: true },
      { name: 'Free', supported: true },
      { name: 'Open-source models', supported: true },
      { name: 'Model selection', supported: true },
    ],
    logoEmoji: '🤗',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-034',
    slug: 'pi',
    name: 'Pi',
    description:
      'A personal AI chatbot from Inflection AI designed to be emotionally intelligent, supportive, and great for casual conversation.',
    category: 'chatbot',
    url: 'https://pi.ai',
    pricing: 'free',
    difficulty: 'beginner',
    bestFor: [
      'Casual, supportive conversation',
      'Mental wellness and reflection',
      'Brainstorming in a friendly tone',
      'Users who want a non-judgmental AI companion',
    ],
    limitations: [
      'Less suited for technical tasks or coding',
      'Knowledge base smaller than ChatGPT or Claude',
      'Limited file/context handling',
    ],
    features: [
      { name: 'Emotionally aware responses', supported: true },
      { name: 'Voice conversations', supported: true },
      { name: 'Completely free', supported: true },
      { name: 'Mobile app', supported: true },
    ],
    logoEmoji: '🤖',
    isBeginnnerPick: true,
  },
  {
    id: 'tool-035',
    slug: 'character-ai',
    name: 'Character.AI',
    description:
      'Chat with AI characters — roleplay, creative writing, and conversational AI with customizable personalities.',
    category: 'chatbot',
    url: 'https://character.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Creative roleplay and fiction',
      'Language practice through conversation',
      'Custom AI character interactions',
      'Fun, casual AI chat experiences',
    ],
    limitations: [
      'Not designed for factual research or coding tasks',
      'Free tier has message limits and wait times',
      'Characters can drift off-topic',
    ],
    features: [
      { name: 'Character creation', supported: true },
      { name: 'Voice generation', supported: true },
      { name: 'Free tier', supported: true, note: 'Message limits apply' },
      { name: 'Mobile app', supported: true },
    ],
    logoEmoji: '🎭',
    isPopular: true,
  },
  {
    id: 'tool-036',
    slug: 'n8n',
    name: 'n8n',
    description:
      'Open-source workflow automation tool — connect apps, build complex automations, and self-host for free with powerful node-based flows.',
    category: 'automation',
    url: 'https://n8n.io',
    pricing: 'open-source',
    difficulty: 'intermediate',
    bestFor: [
      'Self-hosted, privacy-first automation',
      'Complex multi-step data workflows',
      'Developers and technical teams',
      'Cost-effective automation at scale',
    ],
    limitations: [
      'Self-hosting requires server setup knowledge',
      'Steeper learning curve than Zapier',
      'Fewer pre-built templates than Zapier',
    ],
    features: [
      { name: 'Self-hostable', supported: true },
      { name: 'Open-source', supported: true },
      { name: '400+ integrations', supported: true },
      { name: 'Code node (JS/Python)', supported: true },
    ],
    logoEmoji: '🔧',
    isPopular: true,
  },
  {
    id: 'tool-037',
    slug: 'bardeen',
    name: 'Bardeen',
    description:
      'No-code automation platform for browsers — automate repetitive tasks across web apps with AI-enhanced workflows.',
    category: 'automation',
    url: 'https://www.bardeen.ai',
    pricing: 'freemium',
    difficulty: 'beginner',
    bestFor: [
      'Browser-based task automation',
      'Data scraping and enrichment',
      'Sales and recruitment workflows',
      'Non-technical users on web apps',
    ],
    limitations: [
      'Primarily browser-based (limited native app support)',
      'Complex workflows can get tricky',
      'Some integrations are less stable than Zapier',
    ],
    features: [
      { name: 'Browser automation', supported: true },
      { name: 'AI enhancement', supported: 'partial', note: 'Pro plan' },
      { name: 'Free tier', supported: true, note: 'Limited automations' },
      { name: 'Scraping agents', supported: true },
    ],
    logoEmoji: '🔧',
    isBeginnnerPick: true,
  },
];

export function getToolBySlug(slug: string): ToolEntry | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolEntry[] {
  return tools.filter((t) => t.category === category);
}

export function getBeginnerPicks(): ToolEntry[] {
  return tools.filter((t) => t.isBeginnnerPick);
}
